README.md
Fix for the rename in README.md to reflect the new name.
=> Rename the operator name in README.md

CONTRIBUTING.md
=> Add unit test guidelines in CONRIBUTING.md

OWNERS
=> Adding 'ybettan' to the OWNERS file.

cloudbuild.yaml
test-infra PR: https://github.com/kubernetes/test-infra/pull/27461
=> Add the CloudBuild config to build images

docs/lab/README.md, docs/lab/aws/dkms-kmm-kmod.yaml, docs/lab/aws/kmm-kmod.yaml, docs/lab/aws/ubuntu-kmm-kmod.yaml, docs/lab/azure/kmm-kmod.yaml, docs/lab/gce/alpine-kmm-driver.yaml, docs/lab/gce/kmm-driver.yaml, docs/lab/ubuntu/kmm-kmod.yaml
Adds a lab directory with steps, examples and use cases of kmm.
=> Add first document for lab

Makefile, ci/install-ci/kustomization.yaml, config/manager/kustomization.yaml
Match the image name set in #56.
=> Add the -operator suffix to the image name

OWNERS
@zvonkok @adrianchiris Happy to discuss if you want to get involved in KMM. Otherwise, please feel free to /lgtm this PR.
=> Update for kmm OWNERS

Dockerfile.kmm-operator-build
Adding operator-sdk installation
=> Update skipper Dockerfile

.github/workflows/e2e.yaml, controllers/module_reconciler.go, controllers/module_reconciler_test.go, internal/build/job/maker.go, internal/build/job/maker_test.go, internal/build/job/manager.go, internal/build/job/manager_test.go, internal/build/manager.go, internal/build/mock_manager.go, internal/constants/constants.go, internal/sign/job/manager.go, internal/sign/job/manager_test.go, internal/utils/jobhelper.go, internal/utils/jobhelper_test.go, internal/utils/mock_jobhelper.go, main.go
This PR contains the following changes:
1) impement garbage collection for successfull build jobs and pods 2) refactoring jobhelper package and moving build code to use it 3) refactoring/adding unit-test
=> Garbage collection for successfull build jobs

config/rbac/role.yaml, controllers/module_reconciler.go
KMM does not create or delete Modules, neither does it interact with its finalizers.
=> Remove unnecessary permissions on Module

ci/prow/check-api-changes
Fix a duplicated call to target.
=> Fix check-api-changes

bundle.Dockerfile, config/manifests/bases/kernel-module-management.clusterserviceversion.yaml
Those files were supposed to be added to previous PRs but were forgotten.
We now have a CI job to make sure we are not forgetting to push all generated files with each change.
This commit is for making sure we are aligned.
=> Pushing all missing generated files.

PROJECT, config/manifests/bases/kernel-module-management.clusterserviceversion.yaml
That list is used when creating the bundle.
=> Add PreflightValidation to the list of CRDs

docs/labs/gke/gke-ubuntu-nodes.yaml
Fix GKE example removing EKS repo for GCR.
Thanks @qbarrand. Please /cc
=> Fix example in labs

internal/statusupdater/statusupdater.go, internal/statusupdater/statusupdater_test.go, main.go
=> Remove unused API in ModuleStatusUpdater

internal/sign/helper_test.go, internal/utils/replaceStrings.go, internal/utils/replaceStrings_test.go
Apply late comments made on PR #187.
=> Apply last-minute comments to PR 187

docs/mkdocs/preflight/preflight-validation.md
Adding note regarding the Sign section input image and "Push" flag.
=> Fix preflight documentation

docs/mkdocs.yml, docs/mkdocs/developer/index.md, docs/mkdocs/developer/reconciliation_loops.md, docs/mkdocs/developer/use_cases.md, docs/mkdocs/index.md, docs/mkdocs/module_loaders.md, docs/mkdocs/preflight/preflight-validation.md, docs/mkdocs/secureboot/debugging.md, docs/mkdocs/secureboot/index.md, docs/mkdocs/secureboot/secureboot-build-and-sign.md, docs/mkdocs/secureboot/secureboot-secrets.md, docs/mkdocs/secureboot/secureboot-signing.md
=> Adjust formatting, typos, etc

controllers/module_reconciler.go, controllers/module_reconciler_test.go, internal/sign/job/manager.go, internal/sign/job/manager_test.go, internal/sign/manager.go, internal/sign/mock_manager.go
In case Sign job has finished successfully, operator should delete it
=> Add GarbageCollector for successful Sign job

api/v1beta1/preflightvalidation_types.go, config/crd/bases/kmm.sigs.x-k8s.io_preflightvalidations.yaml
=> Fix a typo in the PreflightValidation CRD

controllers/pod_node_module_reconciler.go
This change fixes the `PodNodeModuleReconciler` returning an error when the Pod finalizer update API call returns a not-found error during a reconciliation loop. This led to a new Pod reconciliation request to be queued, which is unnecessary as the specified Pod has been already deleted.
Example of KMM logs that showcase this issue:
```
E0118 12:33:52.351235 1 controller.go:326] kmm "msg"="Reconciler error" "error"="could not delete the pod finalizer: pods \"simple-kmod-bld-quay-ljd6r-pctd9\" not found" "Pod"={"name":"simple-kmod-bld-quay-ljd6r-pctd9","namespace":"simple-kmod"} "controller"="PodNodeModule" "controllerGroup"="" "controllerKind"="Pod" "name"="simple-kmod-bld-quay-ljd6r-pctd9" "namespace"="simple-kmod" "reconcileID"="f4735d8f-854c-4918-ac29-3f60998a6f92"
I0118 …
```
=> Ignore not-found errors on Pod finalizer update

docs/mkdocs/index.md
=> Add README.md to docs

internal/cluster/cluster.go, internal/cluster/cluster_test.go
Sign should wait for build to be completed before syncing.
=> Fix Hub build and sign flow

cmd/manager-hub/main.go, cmd/manager/main.go, config/rbac-hub/role.yaml, controllers/hub/managedclustermodule_reconciler.go
=> Fix KMM Hub scheme and permissions

docs/mkdocs/documentation/deploy_kmod.md
=> Mention Pod Security Admission in the docs

docs/index.html, docs/mkdocs.yml, docs/mkdocs/documentation/troubleshooting.md
Remove obsolete files.
/cc @ybettan
=> Add a troubleshooting section

.github/workflows/e2e.yaml, .github/workflows/test-codecov.yml, Dockerfile, Dockerfile.signimage, cloudbuild.yaml, go.mod
/cc @yevgeny-shnaidman @ybettan
=> Move to Go 1.20

Makefile
=> Add {,un}deploy KMM Hub Makefile rules

.github/workflows/codeql-analysis.yml
=> Build binaries manually for CodeQL

internal/daemonset/daemonset.go, internal/daemonset/daemonset_test.go
Fixing the version labels that are checked during GC n order to find out of device-plugin/module-loader DS needs to be deleted
=> fixing Daemonsets GC

config/certificate/kustomizeconfig.yaml, config/default/kustomization.yaml, config/default/kustomizeconfig.yaml
=> Prefix the webhook secret name with kmm-operator-

Makefile, config/crd-hub/bases/hub.kmm.sigs.x-k8s.io_managedclustermodules.yaml, config/crd/bases/kmm.sigs.x-k8s.io_modules.yaml, config/crd/bases/kmm.sigs.x-k8s.io_preflightvalidations.yaml, config/rbac-hub/role.yaml, config/rbac/role.yaml, config/webhook-hub/manifests.yaml, config/webhook/manifests.yaml
Use the latest release of controller-gen.
=> Upgrade to controller-gen 0.12.0

config/default-hub/kustomization.yaml, config/default-hub/kustomizeconfig.yaml
Follow-up to #383
/cc @ybettan
=> Mount the prefixed secret in the Hub

.github/workflows/e2e.yaml
Fix for some failing jobs such as https://github.com/kubernetes-sigs/kernel-module-management/actions/runs/4935549387/jobs/8822046351?pr=392
/cc @mresvanis
=> Fix the cache key for binaries in CI

OWNERS
Remove mrunalp from the approvers.
/cc @mresvanis @mrunalp
=> Make mresvanis a reviewer and an approver

internal/build/job/maker.go, internal/build/job/maker_test.go
Fixes https://github.com/kubernetes-sigs/kernel-module-management/issues/400
Signed-off-by: Hersh Pathak <hersh.pathak@intel.com>
=> Add KERNEL_FULL_VERSION as a default build argument

.github/actions/collect-troubleshooting/action.yml, config/default-hub/kustomization.yaml, config/default/kustomization.yaml, support/kmm.spec.yaml
Improve data collection using https://troubleshoot.sh/docs/support-bundle/introduction/.
=> Collect a support bundle in CI

cloudbuild.yaml
=> Fix a command in cloudbuild.yaml

config/crd-hub/kustomization.yml, config/crd-hub/patches/cainjection_in_managedclustermodules.yaml, config/crd-hub/patches/webhook_in_managedclustermodules.yaml, config/crd/kustomization.yaml, config/crd/patches/cainjection_in_preflightvalidations.yaml, config/crd/patches/webhook_in_preflightvalidations.yaml, config/default-hub/kustomization.yaml, config/default/kustomization.yaml, config/manager-base/kustomization.yaml
=> Inject the webhook CA into the validated CRDs

docs/mkdocs/documentation/deploy_kmod.md, docs/mkdocs/documentation/install.md, docs/mkdocs/documentation/module_loader_image.md, docs/mkdocs/documentation/ordered_upgrade.md
Add docs for:
- soft dependencies;
- in-tree unloading;
- variable substitution.
Rephrase part of the docs for ordered upgrade.
=> Add 1.1 docs

docs/mkdocs/documentation/ordered_upgrade.md
Fix label names and one bulleted list.
=> Fix the ordered upgrade documentation

docs/mkdocs.yml, docs/mkdocs/documentation/hub_spoke.md, docs/mkdocs/documentation/install.md
/cc @mresvanis @yevgeny-shnaidman
=> Add documentation for Hub & Spoke

internal/filter/filter.go, internal/filter/filter_test.go
Bug sequence as following:
1) Module deployed, with selector targeting only one node
2) ModuleLoader DS created and pod is running
3) Targeted Node rebooted
4) Once Node becomes NotReady, DS is destroyed
5) Node becomes Ready again, but no new ModuleLoader DS is created (bug)
The reason for bug is that once node is in the cluster, all the event for node are Update events. Since the labels do not change between the time that node was NotReady to NodeReady, the events are filtered our and the reconciliation loop is not started
Solution: add another predicate to the filtering of the node event for module reconciler. This predicate will return true in case the Node's condition for Ready type has chnaged and the new condition status is True
=> Fixing ModuleLoader recreation during Node reboot

docs/enhancements/0001-worker-pods.md
Add an enhancement proposal that addresses a number of pain points in the way KMM loads kernel modules in v1.
/cc @yevgeny-shnaidman @mresvanis @ybettan @hershpa
=> Add a proposal for worker Pods in KMM

go.mod
=> Require Go to 1.20 in go.mod

controllers/mock_module_nmc_reconciler.go, controllers/module_nmc_reconciler.go, controllers/module_nmc_reconciler_test.go, controllers/pod_node_module_reconciler_test.go, internal/constants/constants.go
When a Module is deleted, all its ModuleConfigs in all the NMCs should be removed
=> Module deleted scenario in Module-NMC controller

Dockerfile.worker, internal/controllers/nmc_reconciler.go, internal/controllers/nmc_reconciler_test.go
1) Removing privileged and adding SYS_MODULE capability 2) Worker application in worker pod will run as User 0 in order to
be able to run modprobe
=> Reconfigure worker pod capabilities

internal/controllers/nmc_reconciler.go, internal/controllers/nmc_reconciler_test.go
1) setting InProgress to false, when the load Pod is successful
2) adding unit test
=> Fixing Unload Pod not being created on Module deletion

cmd/manager/main.go, internal/controllers/mock_module_nmc_reconciler.go, internal/controllers/module_nmc_reconciler.go, internal/controllers/module_nmc_reconciler_test.go
This implemented by setting Node as the owner of the NMC. In case Node is deleted, NMC will also be deleted
=> Adding Garbage Collection for NMC objects for deleted Nodes

Dockerfile.worker, cmd/worker/main.go, internal/worker/constants.go
Extract images into `/var/run/kmm/images`.
=> Make the images directory a constant

.github/workflows/test-codecov.yml
See https://github.com/codecov/codecov-action/issues/1089
=> Revert codecov action upgrade to v4

internal/controllers/nmc_reconciler.go, internal/controllers/nmc_reconciler_test.go
Currently, in DeletePod is eexcuted per each Pod, and then NMC status is patched once for the the Modules. In case NMC status patch has failed, but the Pod was already deleted, we cannot reconcile NMC status in the next reconciliatio loop, since we don't know what do have the Pod. Since the status will contain InProgress=True, the module will never be reconciled.
In the new flow, all the Pods are deleted only after NMC was successfully patched. In case Pod deletion failed, the reconcile loop will try again, without progressing to NMC spec/status reconciliation. It will also allow for manual intervantion, in case Pod is stuck on some weird error
=> Changing the flow of SyncStatus to accomodate Delete Pod errors

internal/controllers/nmc_reconciler.go, internal/controllers/nmc_reconciler_test.go
Record the service account name as well as the `imageRepoSecret` used in a successful loader Pod into the NMC status so that we can later unload with the same properties.
The service account name is stored as part of the PodSpec.
For the `imageRepoSecret` name, add that volume under a well-known name that can be looked up by `SyncStatus()`.
=> Record more fields into the NMC status

internal/constants/constants.go, internal/controllers/module_nmc_reconciler_test.go
1) removing unused constant ModuleNMCLabelPrefix
2) removing commented code
=> Code cleanup

internal/controllers/nmc_reconciler.go, internal/controllers/nmc_reconciler_test.go
Set requests to 0.5 CPU and 64MiB RAM.
Set limits to 1 CPU and 128MiB RAM.
/cc @yevgeny-shnaidman @mresvanis
=> Set resources for worker Pods

cmd/manager-hub/main.go, cmd/manager/main.go, internal/controllers/mock_nmc_reconciler.go, internal/controllers/nmc_reconciler.go, internal/controllers/nmc_reconciler_test.go, internal/utils/kmmlabels.go, internal/utils/kmmlabels_test.go
Record the ModuleLoaded and ModuleUnloaded events.
Fixes #473 
=> Record kmod load & unload events

cmd/manager-hub/main.go, cmd/manager/main.go, internal/controllers/build_sign_events_reconciler.go, internal/controllers/build_sign_events_reconciler_test.go
=> Rename `JobEventReconciler` to `BuildSignEventsReconciler`

ci/prow/e2e-hub-spoke-incluster-build
Install a specific version of clusteradm as v0.7.0 has a regression.
=> Install clusteradm v0.6.0

config/manager-base/manager.yaml
=> Bump memory limit to 384Mi

.github/workflows/codeql-analysis.yml
Build the worker app in the CodeQL workflow.
=> Install go before initializing CodeQL

.github/workflows/e2e.yaml
Upload both dependencies in one PR.
=> Bump `actions/{up,down}load-artifact`

config/manifests-hub/bases/kernel-module-management-hub.clusterserviceversion.yaml, config/manifests/bases/kernel-module-management.clusterserviceversion.yaml
Switch to the alphabetical order in the `keywords` lists.
/cc @yevgeny-shnaidman 
/cherry-pick release-2.0
=> Add kmm and kmm-hub keywords to the CSV metadata

internal/controllers/build_sign_events_reconciler.go, internal/controllers/build_sign_events_reconciler_test.go, internal/controllers/build_sign_reconciler.go, internal/controllers/build_sign_reconciler_test.go, internal/controllers/device_plugin_pod_reconciler.go, internal/controllers/device_plugin_pod_reconciler_test.go, internal/controllers/device_plugin_reconciler.go, internal/controllers/device_plugin_reconciler_test.go, internal/controllers/mock_build_sign_reconciler.go, internal/controllers/mock_device_plugin_reconciler.go, internal/controllers/mock_module_nmc_reconciler.go, internal/controllers/module_nmc_reconciler.go, internal/controllers/module_nmc_reconciler_test.go, internal/controllers/node_label_module_version_reconciler.go, internal/controllers/node_label_module_version_reconciler_test.go, internal/controllers/preflightvalidation_reconciler.go, internal/controllers/preflightvalidation_reconciler_test.go
Remove boilerplate code and adapt unit tests.
=> Move to `ObjectReconciler`

.github/actions/collect-troubleshooting/action.yml, .github/actions/create-minikube-cluster/action.yml, .github/workflows/e2e.yaml
Configure the artifact name instead of the file name.
=> Move to `upload-artifact` and `cache` v4

cmd/manager-hub/main.go, cmd/manager/main.go, internal/build/manager.go, internal/build/mock_manager.go, internal/build/pod/manager.go, internal/build/pod/manager_test.go, internal/cluster/cluster.go, internal/cluster/cluster_test.go, internal/controllers/build_sign_reconciler.go, internal/controllers/build_sign_reconciler_test.go, internal/controllers/job_gc_reconciler.go, internal/controllers/job_gc_reconciler_test.go, internal/controllers/mock_build_sign_reconciler.go, internal/sign/manager.go, internal/sign/mock_manager.go, internal/sign/pod/manager.go, internal/sign/pod/manager_test.go, internal/utils/mock_podhelper.go, internal/utils/podhelper.go
Revert commit fb1feb5a196d28e4b268172fa2b3b58521ee0a65.
Move the release of the GC delay finalizer to a separate controller.
/cc @mresvanis @yevgeny-shnaidman
=> Change the delayed GC implementation

docs/mkdocs/documentation/configure.md, docs/mkdocs/documentation/troubleshooting.md
=> Mention the webhook-server deployment in docs

docs/mkdocs/documentation/deploy_kmod.md
=> Document the new `inTreeModulesToRemove` field

docs/mkdocs/documentation/preflight_validation.md
=> Document `PreflightValidation` v1beta2

config/manifests/kustomization.yaml, config/olm-hub/kustomization.yaml, config/olm/kustomization.yaml
=> Do not prefix config/manifests resources

config/olm-hub/kustomization.yaml
=> Hub: import the right kustomize base

config/manifests-hub/bases/kernel-module-management-hub.clusterserviceversion.yaml
=> Hub: revert the `InstallMode` change

cmd/manager/main.go
Since this controller can potentially create build or signing jobs, do not start it in managed mode - it is not useful on spokes anyway.
=> Do not start the `PreflightValidation` controller in managed mode

cmd/manager/main.go
We do not build any image in managed mode.
=> Do not start `BuildSignReconciler` in managed mode

config/default-hub/kustomization.yaml, config/default/kustomization.yaml, config/manifests-hub/kustomization.yaml, config/manifests/kustomization.yaml, config/olm-hub/kustomization.yaml, config/olm/kustomization.yaml, config/webhook-server/kustomization.yaml
=> Updating deprecated `kustomization` fields.

Dockerfile.kmm-operator-build
Downgrading skipper image to go 1.22
=> Updating skipper image to correct GO version

OWNERS
=> Remove qbarrand from reviewers

internal/controllers/nmc_reconciler.go, internal/controllers/nmc_reconciler_test.go
When the node upgrade includes kernel upgrade, NMC Spec will change to include new kernel version. In that case NMC controller will try first to create unloader worker pod. Since the unloader worker pod uses the old configuration (from status), which uses the old image, the modprobe in the worker pod will fail, since it won't find kernel module under the /opt/lib/modules/<new kernel> path
This PR fixes the issue by creating unloader pod in case of difference in spec and status of NMC only in case kernels are equal. Otherwise, it creates loader pod, since it means that node was rebooted, and the kernel module is not loaded yet, since the status contains old kernel
=> Fixing module loading during kernel upgrade

internal/controllers/nmc_reconciler.go, internal/controllers/nmc_reconciler_test.go
The following scenario causes worker pods to be stuck during cluster upgrade:
1) kernel module is loaded into the node. NMC contains both spec and status using the current kernel version 2) cluster upgrade starts. As part of the upgrade node becomes
Unschedulable
3) Module-NMC removes Spec from NMC, since the node is Uschedulable 4) NMC controller creates an unload worker pod, since the timestamp of
the ready condition of the node has not been updated yet to a new
value (the node is still not ready).
5) once the node becomes ready, the unload worker pod is scheduled with
the old kernel version and therefore constantly fails.
Solution:
We will skip handling spec, statuses , garbage collection and labelling for the node that are not ready (unschedulable). We will only collect the completed …
=> Fixing yet another race condition during cluster/kernel upgrade

internal/controllers/nmc_reconciler.go, internal/controllers/nmc_reconciler_test.go
In case node it rebooted(for any reason) and the Module CR is being deleted at the same period of time, the following sequence happens: 1) node becomes NotReady
2) module-nmc controller removes Spec from NMC
3) nmc controller does not schedule any unloader pod, since the node is
not ready
4) node becomes ready
5) nmc controller does not schedule unloader pod, since after node
reboot it ignores scheduling unloader pod, since the kernel module is
not loaded anyway
6) no unloader pod running, meaning Status in the NMC is not deleted,
meaning Module CR cannot be finalized, since Status in NMC is present
Solution:
When nmc controller processes Modules without Spec, and the node has been rebooted, the nmc controller will delete the Status from NMC.
=> Fixing Module CR deletion during node reboot

go.mod, go.sum
=> Bumping `golang.org/x/net` to `v0.33.0`.

api/v1beta1/nodemodulesconfig_types.go, config/crd/bases/kmm.sigs.x-k8s.io_nodemodulesconfigs.yaml, internal/controllers/nmc_reconciler.go, internal/controllers/nmc_reconciler_test.go
---
/cc @TomerNewman 
Cherry-picking 2 bug fixes for `release-2.2`
=> Release 2.2.1

.github/workflows/codeql-analysis.yml, .github/workflows/e2e.yaml, .github/workflows/test-codecov.yml
=> Bumping to `go1.23` in Github workflows (CI).

internal/mic/mic.go, internal/mic/mic_test.go, internal/mic/mock_mic.go
Adding 2 function to the interface, that will be later used by controllers, among then MIC controller
=> Adding new functions to MIC interface

internal/mbsc/mbsc.go, internal/mbsc/mbsc_test.go, internal/mbsc/mock_mbsc.go
adding a new interface API that will be used by controllers
=> adding additional API to the mbsc package

cmd/manager/main.go, internal/controllers/module_reconciler.go, internal/controllers/module_reconciler_test.go, internal/mic/mic.go, internal/mic/mic_test.go, internal/mic/mock_mic.go
1) changing ApplyMIC to CreateOrPatch
2) chaning NewModuleImagesConfigAPI to New
=> Changing the names of the APIs of mic package

internal/webhook/module.go, internal/webhook/module_test.go
This commit introduces a validation check in the webhook, to ensure that tolerations with operator: "Exists" do not specify a value, as this is invalid in k8s.
---
/cc @ybettan  @yevgeny-shnaidman
=> Prevent "Exists" tolerations from having a value

internal/buildsign/pod/buildsignpodmanager.go, internal/buildsign/pod/buildsignpodmanager_test.go, internal/buildsign/pod/common.go
---
This is a multi commit (2 commits) PR. Each commit contains its own commit message and the commits will be merged as is (not squashed by Github).
It contains 3 commits:
* Refactoring the way we get the hash annotation for build/sign.
* Refactoring the way we generate the container args for the build pod.
* Renaming the method object name for BuildSignPodManager.
=> Refactor the way we get hash and build args for the build/sign flows.

internal/buildsign/pod/buildsignpodmanager.go, internal/buildsign/pod/buildsignpodmanager_test.go, internal/buildsign/pod/common.go, internal/buildsign/pod/volumes.go
To be used in the build flow as well in the build-sign flow.
---
=> Refactoring the way we generate volume/volumeMounts in build/sign flows.

internal/filter/filter.go, internal/filter/filter_test.go
Previously, nmc controller filtered out all heartbeat-related updates by ignoring changes to node `status.conditions[*].lastHeartbeatTime`.
With this change:
- We now trigger reconciliation when:
- `node.Spec` changes
- `node.metadata.labels` change
- `node.Status.NodeInfo `changes
- The Node condition status transitions.
---
=> Update nmc node predicate to detect Ready transitions and meaningful changes

internal/controllers/mic_reconciler.go, internal/controllers/mic_reconciler_test.go
This commit implements skipping waiting for missing image using image puller pod in case the SkipWaitMissingImage is set in MIC The changes are:
1. In case SkipWaitMissingImage is set, the image puller pod is created with pullPodTypeLabel set to "one-time-pull"
2. The when the pod is in pending state due to a missing image, GetPullPodStatus will return PodFailed, since pullPodTypeLabel is set to "one-time-pull"
3. When updating image status in MIC based on puller pod, in case the puller pod status is failed and the SkipWaitMissingImage is set, then the status is set to ImageDoesNotExists
=> Skip waiting for missing image in case the flag is set

internal/controllers/device_plugin_reconciler.go, internal/controllers/device_plugin_reconciler_test.go
This commit creates an init container definition for the device-plugin daemonset, based on the definitions in the Module CR. In case the ini-container is not defined in the Module CR, then it won't be defined for the device-plugin daemonset
=> Adding init container for device plugin implementation

internal/filter/filter.go, internal/filter/filter_test.go
Currently module reconciler is watching for events on the Node and skips deletions, creations, generics event. On the Update event is looks for labels' changes or that the node becomes schedulable based on the taints. Since filter does not know the tolerations of the Modules, all this code actually does is check if tolerations exist, then check if if tolerations allow scheduling and then checking if there is a difference between new and old conditions in schelabilty of those conditions, and only in that case the module reconciler is scheduled. This means that when the node rebooted, and the node is tainted with the taints whose effect is notSchedule, the module reconciler will never be kicked in, even though there is a Module has a matching toleration. This commit changes the condition …
=> Fixing node events propagated to the module reconciler

docs/mkdocs/documentation/preflight_validation.md
Some statuses has been updated while transitioning to the container-runtime implementation.
---
=> Updating the `PreflightValidation` documentation.

docs/mkdocs/documentation/deploy_kmod.md
=> Documenting the new `initContainer` new option in the `DevicePlugin`.

OWNERS
Adding TomerNewman as a reviewer and approver.
---
/cc @yevgeny-shnaidman @ybettan 
=> Adding TomerNewman to Owners
