OWNERS
ci/prow/lint
ci/prow/unit-tests

~Add contributors of https://github.com/qbarrand/oot-operator.~
Only add @qbarrand for now as other contributors are not members of the `kubernetes-sigs` org yet.
Add empty CI scripts to pass the mandatory CI.

Add qbarrand to reviewers and approvers

---

ci/prow/check-commits-count

Adding a job that enforce a single commit for each PR.
This job will make sure that all commits in a PR were squashed to a single
commit.

Adding a job that enforce a single commit for each PR.

---

controllers/module_reconciler.go
internal/build/job/maker.go
internal/build/job/maker_test.go
internal/build/job/manager.go
internal/build/job/manager_test.go
internal/build/job/mock_maker.go
internal/build/manager.go
internal/build/mock_manager.go

This PR adds additionl flag to the Build APIs
that allows to configure kaniko flag to either
push the image to registry(once it is build),
or skip the push  to registry

Adding build option to disable pushes to registry

---

api/v1beta1/module_types.go
ci/module-kmm-ci-build.template.yaml
config/crd/bases/kmm.sigs.k8s.io_modules.yaml
internal/build/job/maker.go
internal/build/job/maker_test.go

Allow the user to configure which image's tag
from kaniko want to use for the building process.
MGMT-11383

Allow changing image's tag when building with kaniko

---

.github/codecov.yml
.github/workflows/test-build.yml

This PR adds [codecov](https://docs.codecov.com/docs/codecov-yaml) configuration to [ignore](https://docs.codecov.com/docs/codecovyml-reference#ignore) mocks when generating its test coverage report. As a result, the CI step to manually remove mocks from the Go test coverage output can be removed.

Ignore mocks in test coverage report via codecov config

---

controllers/module_reconciler.go
controllers/module_reconciler_test.go
controllers/node_kernel_reconciler_test.go
internal/build/helper.go
internal/build/job/manager.go
internal/build/job/manager_test.go
internal/build/mock_helper.go
internal/module/helper.go
main.go

This PR removes the image existance verification from
Sync API of the build package and moves it into the
handleBuild function of the module reconcilier(prior
to calling the Sync API)

Separate in-cluster build and image existence verification

---

ci/prow/check-commits-count

Prow is cloning the repo using `git clone --mirror ...`.
In addition to that, the changes are directly tested in the `main`
branch, therefore, the only way to get the diff is to add the `upstream`
remote and check the diff against `upstream/main` instead of `main`.

Fixing ci/prow/check-commit-count.

---

api/v1beta1/module_types.go
config/crd/bases/kmm.sigs.k8s.io_modules.yaml
internal/daemonset/daemonset.go
internal/daemonset/daemonset_test.go

It is common for kernel module to come with firmware(s). On immutable operating systems like CoreOS, the standard firmware path `/lib/firmware` is read-only. So, we need to let the kernel know where to lookup firmware file(s).
This change adds the `FirmwarePath` attribute to the `ModprobeSpec` definition and modify the `MakeLoadCommand` and `MakeUnloadCommand` methods to leverage it.
It also adds a `Volume` and a `VolumeMount` to expose the `/var/lib/firmware/<Module.Name>` host directory (created if it doesn't exist) inside the pod. The `/var/lib/firmware` is [the recommended path for firmwares in OpenShift with RHCOS
nodes](https://access.redhat.com/documentation/fr-fr/openshift_container_platform/4.10/html-single/post-installation_configuration/index#rhcos-load-firmware-blobs_post-insta …

Load firmware from the module loader

---

internal/preflight/preflight.go
internal/preflight/preflight_test.go
internal/registry/mock_registry_api.go
internal/registry/registry.go
internal/registry/registry_test.go

Since now we have pull options also in kernel mapping and in Spec, those parameters should now be used in the preflight image verification

Preflight should use PullOptions in image verification

---

internal/daemonset/daemonset.go
internal/daemonset/daemonset_test.go

In most cases shared libraries directory /lib is a dynamic link to /usr/lib but in some other cases as Ubuntu 18.04 LTS or Debian 11, those directories have completely different content. In any case in-tree modules can be found on /lib/modules/KERNEL_VERSION/ so in order to avoid compatibility issues depending which OS Kubernetes nodes are running we should stick to /lib as a mount point for DaemonSet. Also nodeLibModulesPath has been restricted to /lib/modules/KERNEL_VERSION/.

Remove /usr/lib references at DaemonSet

---

CONTRIBUTING.md

There's a typo in unit tests guidelines where `If` is set in place of `It`.

Fix typo in unit test guidelines

---

api/v1beta1/preflightvalidation_types.go
config/crd/bases/kmm.sigs.k8s.io_preflightvalidations.yaml
controllers/preflightvalidation_reconciler.go
controllers/preflightvalidation_reconciler_test.go
internal/preflight/mock_preflight_api.go
internal/preflight/preflight.go
internal/preflight/preflight_test.go
internal/registry/registry.go
internal/registry/registry_test.go
main.go

In case image of the Module is not available or
is does not contain the correct driver version,
preflight will check if Build configuration exists in Module yaml, and if it does, then it will try to build it. In case build is successful, then the module is considered to be verified

adding build verification to preflight

---

ci/prow/check-commits-count

Improving some comment on the 'check-commit-count' job.

---

controllers/module_reconciler.go
controllers/node_kernel_reconciler.go
controllers/node_kernel_reconciler_test.go

Google Kubernetes Engine using COS as nodes set kernel versions ending in a '+' sign which 
breaks KMM as it is not a valid ending for Kubernetes labelling syntax.

Trim plus sign in kernel versions

---

api/v1beta1/preflightvalidation_types.go
config/crd/bases/kmm.sigs.k8s.io_modules.yaml
config/crd/bases/kmm.sigs.k8s.io_preflightvalidations.yaml
controllers/preflightvalidation_reconciler.go
controllers/preflightvalidation_reconciler_test.go
internal/filter/filter.go
internal/preflight/mock_preflight_api.go
internal/preflight/preflight.go
internal/preflight/preflight_test.go

1) add a field to the Preflight CRD spec , that signifies if customer
wants to push the image during preflight verification
2) add support for image push during preflight Build stage 3) add Generator filter to preflight Watch, to skip being scheduled
on Preflight status changes

Adding support for image push during preflight build verification

---

Makefile

`kustomize` has been embedded in the `kubectl` command, so we can use
`kubectl` in most of the places.

Replacing 'kustomize' binary with 'kubectl kustomize' binary.

---

config/rbac/role.yaml
controllers/module_reconciler.go
go.mod
go.sum
internal/build/job/maker.go
internal/build/job/maker_test.go
internal/build/job/manager.go
internal/build/job/manager_test.go
internal/build/job/mock_maker.go

Currently once the Build job is created, it cannot be changed. Therefore even if user changes Build configuration in the module, the existing job will not be changed. This fixes it by doing the following 1) when job is created, Template data is hashed and saved as annotation
in the job
2) when checking job status, hash of the new contents is compared
to the existing one
3) in case hashes differ, the current job is deleted, which will
trigger new job creation in the next reconcilation loop
4) in case job is in progress, reconcile should use RequeueAfter
field with predefined value, otherwise it will cause exponential
requeing timeouts

Update of Build configuration in Module should trigger new Job

---

internal/build/job/manager.go
internal/build/job/manager_test.go

When we delete build job (due to Spec change) while its pods are still running/failed, those pods are not deleted and will stay there untill deleted manually. This PR adds a Propagate option to the Delete API call that will instaract GC to remove the pods of the deleted job

Fixing build job deletion, in case its pods are still running

---

.gcloudignore

Explicitly include .git in Google Cloud Builds
To include VCS data in the controller binary, our image build process
requires .git to be present in the working directory.
Google Cloud Build, the system used by the Kubernetes project to build
container images, ignores .git by default.
Explicitly include .git in the GCB environment through a .gcloudignore
file.
Reference: https://github.com/GoogleCloudPlatform/cloud-builders/issues/236#issuecomment-374629200

Include .git in image builds

---

controllers/module_reconciler.go
controllers/module_reconciler_test.go
internal/build/job/manager.go
internal/build/job/manager_test.go
internal/build/manager.go
internal/build/mock_manager.go
internal/preflight/preflight.go
internal/preflight/preflight_test.go

The name of the image to build is assumed to be km.ContainerImage in several places in the code, this PR centralises that assumption into a single point in Reconcile(). This should make the code more maintainable in the future when that assumption may no longer be true.  
E.g if we add a signing stage to the image build process, then build itself needs to produce an intermediate image that is consumed by the signing job, and it is the signing job that needs to produce km.ContainerImage. 
(I also notice we have a module.spec.moduleLoader.container.containerImage field, which is presumably meant to be a default, but we cannot use it while the km.ContainerImage assumption is made in lots of different places, )

centralise the name of the image to build in the controller

---

Makefile
config/manager/kustomization.yaml

The images that we build are tagged with `latest`, not `main`.

Make latest the default tag

---

internal/build/job/maker_test.go
internal/build/job/manager.go
internal/constants/constants.go

This PR adds a third label to kubernetes job objects created by kmmo for future proofing.
Currently jobs are labelled the module.name and target-kernel, and these are used to search for the job to ensure its creation, completion etc.
The manger searching for these jobs has no other way of determining which job it should be managing.
If we add multiple jobs into the build pipeline (e.g. a signing job) the build manager has no way of distinguishing between the different jobs, so when it searches for completed jobs it will detect finished signing jobs as if they were finished build (kaniko) jobs, and vice versa. This would lead to much confusion and the pipeline not running through its stages correctly.
This commit adds a third "kmm.node.kubernetes.io/build-stage" label that is set to …

Add an extra label to the build job to label the stage of the build

---

ci/kmm-kmod/Makefile

Modify Makefile to use running kernel version if KERNEL_SRC_DIR is not set.

Modify Makefile in kmm-kmod

---

Dockerfile.signimage
Makefile
cmd/signimage/README.md
cmd/signimage/signimage.go
internal/registry/mock_registry_api.go
internal/registry/registry.go
internal/registry/registry_helper_test.go

This commit adds a stand alone binary (signimage.go) and an associated Dockerfile that together will provide the image for use in the signing job.
The dockerfile compiles signimage, and retrieves the sign-file binary from the kernel-devel package. sign-file is the binary provided by the kernel developers for signing kmods, and while its operation is not super-complex and could be handled within signimage.go, we use it to ensure maximum compatibility. 
The signimage.go binary takes an image name, pulls it down, loops through each file in each layer and if its a kernel modules extracts it to a temporary directory, and runs sign-file on it. All signed kmods are then added back as a (single) new layer, and the new image pushed back to the registry.
It is intended that this output image is the …

add code/dockerfile for building the secureboot signing job image

---

ci/kmm-kmod/Makefile

Add EXTRA_MODULE variable to Makefile so extra module name
can be set in args.

Add EXTRA_MODULE variable to kmm-kmod Makefile

---

internal/daemonset/daemonset.go
internal/daemonset/daemonset_test.go

This PR fixes failing firmware requests, which are caused by the additional firmware path directory, named after the Module CR, which is created by KMM when copying the firmware files from the module-loader container to the host directory (and default firmware search path) `/var/lib/firmware`.
Modules request firmware files using a relative path, e.g. `vendor/device/firmware.bin`, which is appended to the default firmware search path. The additional firmware path directory makes the firmware requests unresolvable.
Specifically, this change:
- removes the additional firmware path directory, named after the Module CR
- ensures that only the copied firmware files are removed after the module is unloaded and non-empty firmware directories are skipped (this was not needed before, because each …

Fix failing firmware requests

---

ci/prow/check-api-changes

When API code changes, we need to regenerate CRD configs using make generate manifests.
This script checks that regenerated files are pushed in the same PR which changes the API
code so CRD configs are not merged in next unrelated PRs.

Add check-api-changes script to CI

---

config/default/kustomization.yaml
config/manager/controller_manager_config.yaml
main.go

This change enables controller configuration via a versioned config file, referred to as "component config". Configuration options can now be passed to the controller by a `ConfigMap`.
- https://book.kubebuilder.io/component-config-tutorial/tutorial.html

Enable configuration flags via component config

---

controllers/module_reconciler.go
controllers/module_reconciler_test.go
internal/metrics/metrics.go
internal/sign/job/manager.go
internal/sign/job/manager_test.go
main.go

This is the last part of the secureboot signing code and provides the required code in the reconcile loop to detect if the CR contains a Sign stanza, and if so makes the required calls into the internal/sign library to instantiate and manage the signing job.
- It changes the handleBuild() function to check if a Sign stanza is defined, if so it outputs an intermediate image named spec.containerImage+"-unsigned"
- It then adds a handleSigning() function that will consume this intermediate image, run the signing job and produce the final spec.containerImage image
It is this final image that is then loaded by the daemonset.
It also makes sure is Sign is not defined handleBuild() still does the right thing and handleSigning() consumes sign.UnsignedImage if a Build stanza is not defined.

Add code to the reconcile loop for signing of kmods for secureboot.

---

.github/workflows/e2e.yaml
api/v1beta1/module_types.go
api/v1beta1/zz_generated.deepcopy.go
ci/kmm-kmod-dockerfile.yaml
ci/module-kmm-ci-build.template.yaml
config/crd/bases/kmm.sigs.k8s.io_managedclustermodules.yaml
config/crd/bases/kmm.sigs.k8s.io_modules.yaml
config/rbac/role.yaml
controllers/module_reconciler.go
internal/build/helper.go
internal/build/helper_test.go
internal/build/job/maker.go
internal/build/job/maker_test.go
internal/build/job/manager.go
internal/build/job/manager_test.go
internal/build/job/mock_maker.go
internal/constants/constants.go
internal/module/kernelmapper_test.go
main.go

Currently dockerfile is defined a multiline string in the Build field of the KernelMapping. This PR does the following: 1) dockerfile is now defined in a dedicated configmap (created by customer)
with the key being: dockerfile
2) Build struct now contains reference to the ConfigMap, instead of
a string
3) change the flow of e2e workflow for the in-cluster build
to use the new configuration

Moving Build Dockerfile to be defined in the ConfigMap

---

internal/sign/job/signer_test.go

The code is using the same global module object for all tests, which means that if one of the specs change the module, it affects all other tests.
Each spec should be tested with a clean module.
How did it impact the code before the change:
Running
```
make unit-test TEST=github.com/kubernetes-sigs/kernel-module-management/internal/sign/job
```
was working only because all the tests were running one after the other, once we focused on the `should set correct kmod-signer flags` spec only it was failing because it was expecting some state which was modified by another spec that run before it.

Fixing a bug in the 'sign' UT.

---

ci/prow/check-api-changes

Change the use of make generate manifests for make generate manifests bundle so
we make sure we push both targets in the PRs.

Fix check-api-changes script

---

config/rbac/role.yaml
controllers/node_kernel_clusterclaim.go
controllers/node_kernel_clusterclaim_test.go
internal/filter/filter.go
internal/filter/filter_test.go

This reconciler collects all kernel versions running in the cluster and populates a ClusterClaim with them.
To minimize updates to the ClusterClaim (which triggers a sync back to the ManagedCluster), kernel versions are sorted alphabetically and separated by a new line.
This controller is not started by any manager yet because we still have to determine if we add it to the mainline KMM or if we create a dedicated image for Spoke clusters.
/cc @mresvanis @yevgeny-shnaidman @ybettan

Add the kernel - ClusterClaim reconciler

---

.github/actions/collect-troubleshooting/action.yml
.github/workflows/e2e.yaml
ci/prow/e2e-crd-variable
ci/prow/e2e-incluster-build
ci/prow/e2e-prebuilt-kernel-module
ci/prow/e2e-prebuilt-kernel-module-two-nodes

In order to sync CI jobs with m/s and make code reusable
through components, actions scripts tests are migrated to prow scripts.

Migrate e2e tests

---

Dockerfile.signimage
Makefile
cloudbuild.yaml

Use alpine base images for a smaller footprint (46 vs 209MB).
Rework the Dockerfile for better caching.
/cc @chr15p

Build signer images in CI

---

controllers/module_reconciler.go
controllers/module_reconciler_test.go
internal/build/helper.go
internal/build/helper_test.go
internal/build/job/maker.go
internal/build/job/maker_test.go
internal/build/job/manager.go
internal/build/job/manager_test.go
internal/build/job/mock_maker.go
internal/build/manager.go
internal/build/mock_helper.go
internal/build/mock_manager.go
internal/module/helper.go
internal/module/helper_test.go
internal/preflight/preflight.go
internal/preflight/preflight_test.go
internal/sign/helper.go
internal/sign/helper_test.go
internal/sign/job/manager.go
internal/sign/job/manager_test.go
internal/sign/job/mock_signer.go
internal/sign/job/signer.go
internal/sign/job/signer_test.go
internal/sign/manager.go
internal/sign/mock_helper.go
internal/sign/mock_manager.go
internal/utils/jobhelper.go
internal/utils/jobhelper_test.go
internal/utils/mock_jobhelper.go
main.go

This PR decouples the `build` and `sign` internal APIs from the `ModuleReconciler`, in order to be able to use them in other reconcilers as well, i.e. the `ManagedClusterModuleReconciler`.

Decouple build and sign from ModuleReconciler

---

config/rbac/role.yaml
controllers/module_reconciler.go

This fix adds the `watch` permission for `ConfigMap`s to the `Module` reconciler, in order to be able to successfully `client.Get()` the build Dockerfile `ConfigMap`. This `client.Get()` fails because the contoller-runtime client reads from its cache, instead of directly from the API server. The client needs the `watch` permission, in order to be able to build its cache.
- https://github.com/kubernetes-sigs/controller-runtime/issues/1156

Fix module reconciler not being able to watch for ConfigMaps error

---

controllers/preflightvalidation_reconciler.go
internal/preflight/preflight.go

This PR add a watch to preflight controller in order to react quicker to the Build/Sign completions. In addition the reconciliation scheduling timeout has been increased to 3 minutes

add job watch to preflight controller setup

---

internal/constants/constants.go
internal/sign/job/manager.go
internal/sign/job/manager_test.go
internal/sign/job/mock_signer.go
internal/sign/job/signer.go
internal/sign/job/signer_test.go
main.go

Sign job annotation is used for deciding whether update flow should be executed on the job ( deletion and creation anew with new parameters). Currently the code includes verification of currently running job hash versus the new parameters hash, but the actual code that sets the hash annotation during job template is missing. This PR does the following:
1) add hash annotation calculation during job template creation 2) unit test

Fixing sign job hash annotation

---

api/v1beta1/preflightvalidation_types.go
config/crd/bases/kmm.sigs.k8s.io_preflightvalidations.yaml
internal/module/helper.go
internal/preflight/mock_preflight_api.go
internal/preflight/preflight.go
internal/preflight/preflight_test.go
main.go

This PR add the sign verification stage to the preflight: in case image verification has failed and either build section is not defined or build verification was successful, preflight will now verify sign , if it was defined in the Module

Adding sign verification to the preflight flow

---

Dockerfile.signimage
go.mod

Align `go.mod` with the version we use to build images.
Use the same Alpine version to build and run `signimage`.

Bump some dependencies

---

internal/filter/filter.go

This PR fixes possible panics when the [logr.Error()](https://pkg.go.dev/github.com/go-logr/logr#Logger.Error) has an `error` instead of key-value string pairs as its third and onwards arguments.

Fix logr.Error accepting key-value pair instead of error

---

config/rbac/role.yaml
controllers/node_kernel_clusterclaim.go

The `NodeKernelClusterClaim` reconciler requires permissions and leverages client caching on `ClusterClaim` resources. This change adds permissions to `[create,get,list,watch]` `ClusterClaim` resources, but only `[patch,update,delete]` on the specific `ClusterClaim` that the reconciler itself has created.

Adjust ClusterClaim permissions to enable creation and caching

---

internal/daemonset/daemonset.go
internal/daemonset/daemonset_test.go

Currently the firmware path defined in the Module CR is copied into the /var/lib/firmware host path, including the the rightmost directory. Since customed firmware base loading directory for kernel modules is /var/lib/firmware, it means that kernel modules that are expecting their firmware to be located unnder base path (/var/lib/firmware) cannot be run, since current implementation will always contain at leas one additional directory under /var/lib/firmware. This PR changes implementation, so that, if needed, firmware file can be copied directly under the base path (/var/lib/firmware)

Fixing FIRWARE files/directories loading

---

Makefile

To make sure u/s and m/s are always using the same version without the need of manually installing and maintaining `operator-sdk` with the same version on u/s infra and on m/s infra.

Installing `operator-skd` via Makefile.

---

docs/mkdocs/secureboot/debugging.md
docs/mkdocs/secureboot/index.md
docs/mkdocs/secureboot/secureboot-build-and-sign.md
docs/mkdocs/secureboot/secureboot-secrets.md
docs/mkdocs/secureboot/secureboot-signing.md

Add some (basic) documentation for how to use kmod signing within kmm
This covers the build-and-sign, and the sign-prebuilt-image use cases

add user documentation for secureboot signing

---

Makefile
cloudbuild.yaml

Do not install operator-sdk manually in cloudbuild.yaml.
/cc @ybettan

Create ./bin when installing operator-sdk

---

cloudbuild.yaml

Use a script syntax supported by the older version of gcloud bundled in the k8s builder image.
Push manager images manually so that they are available in the build-bundles step that looks for their SHA.
/cc @yevgeny-shnaidman @ybettan @mresvanis

Fix the Cloud Build config

---

.github/workflows/e2e.yaml
ci/kmm-kmod-dockerfile.yaml
ci/module-kmm-ci-build.template.yaml
ci/prow/e2e-incluster-build

Until now, we were just building the driver container in the Github
runner, loading it into minikube and then the Dockerfile loaded as a
ConfigMap was just downloading that image, adding some files and pushing
instead of actually build the driver container in cluster.
This commit is fixing that flow.

Making the e2e-incluster-build job to actually build in cluster.

---

config/manager-base/manager.yaml
internal/build/job/maker.go
internal/build/job/maker_test.go
internal/sign/job/signer.go
internal/sign/job/signer_test.go

This allows us to patch those variables with the digest equivalent of the images.
Unfortunately `operator-sdk` does not seem to identify them properly for an unknown reason; that means that the images are not listed under the CSV's `relatedImages` field, nor are they automatically replaced with their digest equivalent.

Configure related images via environment variables

---

internal/sign/helper.go
internal/sign/helper_test.go
internal/sign/job/signer.go
internal/sign/job/signer_test.go
internal/sign/mock_helper.go
internal/utils/replaceStrings.go

filesToSign (the filepaths of the kmods to sign) and unsignedImage (the name of the image that contains the kmods if its not built in cluster) both normally would contain the kernel version, this commit allows the embedding of "$(KERNEL_VERSION)" in them and have it replaced with the actual kernel version

add support for KERNEL_VERSION replacement for signing

---

ci/module-kmm-ci-build.yaml
ci/prow/e2e-incluster-build

The decision to remove it was a mistake. It was confused with `imageRepoSecret`.
The build arg is supposed to be available to the `build` Dockerfile at `/run/secrets/build-secret/filename`.

Adding back the `build-secret` to the e2e test.

---

api-hub/v1beta1/managedclustermodule_types.go
cmd/manager-hub/main.go
config/crd-hub/bases/hub.kmm.sigs.x-k8s.io_managedclustermodules.yaml
controllers/hub/managedclustermodule_reconciler.go
controllers/hub/managedclustermodule_reconciler_test.go
internal/manifestwork/manifestwork.go
internal/manifestwork/manifestwork_test.go
internal/manifestwork/mock_manifestwork.go
internal/statusupdater/mock_statusupdater.go
internal/statusupdater/statusupdater.go
internal/statusupdater/statusupdater_test.go

This PR adds the implementation of the `ManagedClusterModuleStatus`. The latter reflects the number of desired, applied and degraded `ManifestWork` CRs owned by the respective `ManagedClusterModule` CR.

Implement ManagedClusterModuleStatus for KMM-Hub

---

internal/manifestwork/manifestwork.go
internal/manifestwork/manifestwork_test.go

This change configures the `ManifestWork`, via its `FeedbackRules` [field](https://github.com/open-cluster-management-io/api/blob/b57d18bd356abdf57633bd2cfcc227656f72418f/work/v1/types.go#L82), to report back to the Hub the `Module.Status`. This way, admins on the Hub can check the applied `ManifestWork`s for the status of the Spokes' `Module`s. 
The `ManifestWork` `FeedbackRules` can be configured either with the `WellKnownStatusType` or the `JSONPathsType`. The `Module` CRD is not a well-known Kubernetes resource and the `JSONPathsType` accepts only `Integer`, `String` and `Boolean` types. As such, we have to explicitly define all fields of the `Module.Status` to be included in the `ManifestWork`'s `FeedbackRules`.
https://open-cluster-management.io/concepts/manifestwork/#status-tracking …

Configure the ManifestWork to report the Module.Status

---

cmd/signimage/signimage.go
internal/sign/job/signer.go
internal/sign/job/signer_test.go
internal/utils/volume_helper.go

Re-work secret handling for pulling and pushing images Add support for dockerconfigjson and dockercfg style secrets Add support for multiple keys in a single secret (useful for pulling and pushing to different registries)
This also sets the stage for allowing service account secrets
We do this by mounting secrets in their own directories then reading all the files (keys) in that dir

Improve push/pull secret handling in signing

---

controllers/hub/managedclustermodule_reconciler.go
controllers/node_kernel_clusterclaim.go
internal/cluster/cluster.go
internal/cluster/cluster_test.go
internal/constants/constants.go
internal/filter/filter.go
internal/filter/filter_test.go

This change updates the `ManagedClusterModule` reconciler's `ManagedCluster` watch predicate, in order to enqueue update events of changed KMM `ClusterClaim`s. This way whenever a new kernel version is available on a `ManagedCluster`, the `ManagedClusterModule` reconciler will reconcile the affected `ManagedClusterModule`s.

Adjust ManagedClusterModuleReconciler ManagedCluster watch predicate

---

ci/kmm-kmod-dockerfile.yaml
ci/prow/e2e-incluster-build

Instead of checking that the secrets are available on the `kaniko` pod we should check that the secret files are available in the Dockerfile itself.

Updating the `in-cluster-build` job to correctly use build secrets.

---

cmd/signimage/signimage.go
internal/sign/job/signer_test.go

the error from the sign-file binary was getting lost because it wasn't returned through the stack call correctly. This commit fixes that by passing the message up.
Also remove a couple of commented out code lines. (these were picked up by downstream code review)

log error if sign-file fails

---

internal/build/job/maker.go
internal/build/job/maker_test.go
internal/sign/job/signer.go
internal/sign/job/signer_test.go

In the default configuration, once the failed container of the pod is restarted 6 times, and after the final failure it is deleted. This PR changes the policy to never restart, and the backoff limit to 0, meaning that after first failure, the pod/container won't be restarted, but the failed pod itself will be kept in the cluster for future debugging

Configuring the build and sign job backoff and restart policies

---

ci/prow/check-commits-count

Fixing `check-commits-count` to work on other branches than `main`.

---

docs/mkdocs/developer/index.md
docs/mkdocs/developer/use_cases.md

Removing section regarding pre-stop lifecycle that needs to be supplied by user and updatting the correct prefixes for labels and apiVersion

Fixing documentation

---

config/rbac/device_plugin_service_account.yaml
config/rbac/kustomization.yaml
config/rbac/module_loader_service_account.yaml
controllers/module_reconciler.go
controllers/module_reconciler_test.go
internal/daemonset/daemonset.go
internal/daemonset/daemonset_test.go
internal/daemonset/mock_daemonset.go

The ModuleLoader and DevicePlugin ServiceAccounts created in the operator's namespace via the OLM bundle and used as default ServiceAccounts in the respective workloads are unnecessary. Users are free to use the default namespace ServiceAccount or any ServiceAccounts they dim necessary.
If Pod Security Admission is enabled in the cluster, an administrator needs to configure the level for the namespace where the `Module` is deployed for the ModuleLoader and device plugin pods to work.
- https://kubernetes.io/docs/concepts/security/pod-security-admission/

Remove unnecessary ServiceAccounts used in the operator namespace

---

internal/utils/replaceStrings_test.go

Ginkgo / Gomega require assertions to be within `It` blocks.

Wrap assertions into Ginkgo `It` blocks

---

docs/mkdocs.yml

Current [Edit on GitHub](https://github.com/kubernetes-sigs/kernel-module-management/edit/main/docs/index.md) link lands on a 404 because, I think, the docs are under `mkdocs` directory.

Fixes edit-uri for documentation

---

controllers/module_reconciler.go
controllers/module_reconciler_test.go
internal/cluster/cluster.go
internal/cluster/cluster_test.go
internal/module/kernelmapper.go
internal/module/kernelmapper_test.go
internal/module/mock_kernelmapper.go
internal/preflight/preflight.go
internal/preflight/preflight_test.go

Currently KernelAPI consists of 4 functions, which are always used together in a sequence. This redifines the KernelAPI interface to contain only one functions that does everything the previous 4 functions were doing. In addtion a private helper interface is defined, and its function are used by the KernelAPI interface

Simplifying KernelAPI interface

---

cmd/manager/main.go
controllers/module_reconciler.go
controllers/module_reconciler_test.go
controllers/preflightvalidation_reconciler.go
controllers/preflightvalidation_reconciler_test.go
internal/metrics/metrics.go
internal/metrics/mock_metrics_api.go
internal/statusupdater/statusupdater.go
internal/statusupdater/statusupdater_test.go

Up to now, the metric were mainly refelcting the current progress of customer's Module, which was not very useful, since customers do not look at them. This PR changes the metrics so as to supply the info regarding KMMO usage by the customer. The following metrics are gathered: 1) number of Modules deployed on the cluster
2) number of modules with in-cluster build capabilty 3) number of module with in-cluster sign capability 4) number of modules deploying device plugin
5) if the preflight capability is used on the cluster 6) modules that are using Morprobe arg configuration ( raw and non-raw)
and which configuration they are using

Changing the metrics flow

---

docs/mkdocs/documentation/secure_boot.md

Fixing the build Configmap example in the secture_boot.md The key for the Configmap's data should be 'dockerfile' and not 'Dockerfile'

Documentation fix

---

Makefile
ci/module-kmm-ci-build-sign.yaml
internal/build/job/maker.go
internal/build/job/maker_test.go
internal/module/kernelmapper.go

Expose module's name and namespace  through build args and use them in the `containerImage`
#103

Expose module's name and namespace

---

api-hub/v1beta1/managedclustermodule_types.go
api/v1beta1/module_types.go
config/crd-hub/bases/hub.kmm.sigs.x-k8s.io_managedclustermodules.yaml
config/crd/bases/kmm.sigs.x-k8s.io_modules.yaml
internal/statusupdater/statusupdater.go
internal/statusupdater/statusupdater_test.go

This change includes the following:
- mark the DaemonSetStatus fields are optional
- replace update with patch for the {Module,ManagedClusterModule} status subresource
It resolves the issue of the reconciliation returning an StatusConflict error when trying to update the status of a {Module,ManagedClusterModule} CR, which in turn leads to multiple reconciliation requests of a CR just to update its status subresource successfully.
Context
-------
When updating the {Module,ManagedClusterModule} status subresource, the following error usually comes up:
"the object has been modified; please apply your changes to the latest version and try again"
This error is caused by the controller-runtime cache being stale at the time of the status update, i.e. the resourceVersion of the …

Patch instead of update Module and ManagedClusterModule status

---

.github/actions/collect-troubleshooting/action.yml
.github/workflows/e2e.yaml
Makefile
ci/install-ci/kustomization.yaml
internal/sign/job/signer_test.go
internal/sign/job/templates/Dockerfile.gotmpl

Fix the path to the sign-file binary.
Build the signing image in CI.

Fix signing Dockerfile

---

api/v1beta1/module_types.go
config/crd-hub/bases/hub.kmm.sigs.x-k8s.io_managedclustermodules.yaml
config/crd/bases/kmm.sigs.x-k8s.io_modules.yaml

Version field will be used in the ordered upgrade scenario. It signifies the current version of the kernel module.
It should be updated together with the new image in the appropriate kernel mapping. Its update will start the process of the ordered upgrade

Adding Version field to Module CRD

---

internal/constants/constants.go
internal/utils/moduleversionlabels.go
internal/utils/moduleversionlabels_test.go

This PR add the following 3 labels, that will be used during ordered update process:
1) kmm.node.kubernetes.io/version-label-module_<namespace>_<name> 2) kmm.node.kubernetes.io/version-label-module-loader_<namespace>_<name> 3) kmm.node.kubernetes.io/version-label-device-plugin_<namespace>_<name>
The first label is set by the user and signifies on which node which version should be run. The second and the third labels are managed by KMMO and are used as node selectors for module loader and device plugin damoensets accordingly. This PR also include utils functions for generating the full labels' names and for extracting namespace and name data from labels
Part of [263](https://github.com/kubernetes-sigs/kernel-module-management/issues/263)

Adding module version labels definitions

---

docs/mkdocs/documentation/secure_boot.md

Update broken links in secure_boot.md (https://github.com/kubernetes-sigs/kernel-module-management/issues/337)
Documentation improvement.
/documentation
Signed-off-by: Hersh Pathak <hersh.pathak@intel.com>

Update broken links in secure_boot.md

---

controllers/pod_node_module_reconciler.go
controllers/pod_node_module_reconciler_test.go
internal/daemonset/daemonset.go
internal/daemonset/daemonset_test.go
internal/daemonset/mock_daemonset.go

Adding the namespace to the `<module>.ready` label.
This is handy when there are multiple modules on each node and make it
easier to determine where is each module.
Also, solving a race condition in a new pod was created while the old
pod of a `moduleLoader` is being terminated which resulted in the
`<module>.ready` label to be deleted.
---
Fixes https://github.com/kubernetes-sigs/kernel-module-management/issues/315

Adding the namespace to the `<module>.ready` label.

---

controllers/module_reconciler.go
controllers/module_reconciler_test.go
internal/api/moduleloaderdata.go
internal/daemonset/daemonset.go
internal/daemonset/daemonset_test.go
internal/daemonset/mock_daemonset.go
internal/module/kernelmapper.go

This PR add handing of the Version of the module in the creation of DevicePlugin and ModuleLoader DaemonSets. The following was added: 
1) setting the Module's Version in the ModuleLoaderData
2) adding Version the hash of DevicePlugin/ModuleLoader daemonset's name
3) adding module version label to the labels of DevicePlugin/ModuleLoader daemonsets
4) changing DS garbage collection to remove DS that does not contain the current
version label, and has no more available pods

handling Version change in DevicePlugin and ModuleLoader DaemonSets

---

ci/prow/test-deploy

Reverts kubernetes-sigs/kernel-module-management#353
If someone breaks the deployment flow but inserting new dependencies and
decide that the "fix" is to install those dependencies manually in the
e2e test, then he will also probably install the dependency manually in
this test instead of adding the dependency installation to the
`kustomization` overlay, therefore, this test doesn't have any
additional value.

Revert "Adding a `prow` script to test a basic deployment."

---

internal/daemonset/daemonset.go
internal/daemonset/daemonset_test.go

Setting the SharedProcessNamespace to true, which will cause the PID 1 process of the pod container to be pause. Puase process is trapping SIGTERM, which will allow kubelet to destroy the container process immediately, without 30 seconds timeout

Fixing termination timeout for module loader pods

---

internal/daemonset/daemonset.go
internal/daemonset/daemonset_test.go

This PR allows defining the load order of multiple independent kernel modules in one KMM Module. The order is defined as a list in the ModulesLoadingOrder field of the ModprobeSpec. The first module will be loaded last, the last one in the list will be loaded first. It is implement by using DownwardAPI: module loader pod template contains is added an annotation that contains the /etc/modprobe.d/softdep format, and then this annotation is added as a file to module loader's pod filesystem using Downward API

Loading multiple independent kernel modules in one KMM Module

---

.github/workflows/e2e.yaml
ci/kmm-kmod-dockerfile.yaml

This PR replaces [ubuntu-latest](https://github.com/actions/runner-images#available-images) with `ubuntu-20.04` explicitly in the CI e2e Github actions and Dockerfiles. 
When using `ubuntu-latest`, which is currently pointing to `ubuntu-22.04`, we have kernel version `5.15.0-1036-azure` on the VM, but there is no `linux-headers-5.15.0-1036-azure` package in the ubuntu-22.04 repos. So we we get an error when building the CI kmod using the `ubuntu:latest` (also pointing currently to `ubuntu:22.04`) container image, because the respective linux headers cannot be installed. With Ubuntu 20.04 LTS  this is not an issue.  
Example CI error:
```log
E: Unable to locate package linux-headers-5.15.0-1036-azure
E: Couldn't find any package by glob 'linux-headers-5.15.0-1036-azure'
E: Couldn't find …
```

Use ubuntu-20.04 explicitly in CI e2e tests instead of ubuntu-latest

---

.github/workflows/e2e.yaml
ci/prow/e2e-hub-spoke-incluster-build

This change updates the CI e2e-hub test to wait for the `clusteradm join` command to succeed asynchronously. Waiting for it synchronously sometimes leads to errors like the following:
```log
+ clusteradm join --hub-token *** --hub-apiserver https://192.168.49.2:8443 --wait --cluster-name minikube
Error: no matches for kind "Klusterlet" in version "operator.open-cluster-management.io/v1"
```
This errors comes from [clusteradm](https://github.com/open-cluster-management-io/clusteradm/blob/95f9d75af1b20d6c1f04298a8e01b5941cd7a867/pkg/cmd/join/exec.go#L261-L265) itself and the only workaround we can do is run the `clusteradm join` command and wait/watch asynchronously for the relevant Kubernetes resources, that indicate a successful join, to be available.
This PR also removes the unneeded …

Update CI e2e-hub test

---

cmd/manager-hub/main.go
internal/manifestwork/manifestwork.go
internal/manifestwork/manifestwork_test.go

This PR fixes an issue when KMM Hub fetches the container image digest with registry authentication creds and fails due to searching the registry creds secret in the spoke's namespace instead of the KMM Hub operator namespace.

Use operator namespace when hub fetches the image digest

---

Dockerfile.kmm-operator-build

1) removing operator-sdk, kustomize and mockgen, since makefile is
using the once installed under the repo/bin directory
2) update the mockgen version

Update skipper configuration

---

Makefile
ci/prow/check-api-changes
cloudbuild.yaml
config/manager-base/kustomization.yaml
config/manager-base/kustomizeconfig.yaml
config/manager-base/manager.yaml

Add the `IMAGE_TAG` variable to `Makefile`.
Use that variable in `cloudbuild.yaml` to reference the correct images when creating the bundle.
/cc @mresvanis @ybettan

Set the tag of related images when building bundles

---

Makefile
ci/prow/check-api-changes
cloudbuild.yaml
config/manager-base/kustomization.yaml
config/manager-base/kustomizeconfig.yaml
config/manager-base/manager.yaml

Do not run make bundle in `ci/prow/check-api-changes` since we do not version bundles.
Do not push to the `latest` tag.
Cherry-pick of 25eb240526db4b0e7da234d6348beebc365bc56d
/cc @mresvanis

Set the tag of all images when building bundles

---

Makefile
config/manifests-hub/bundle-metadata/dependencies.yaml
config/manifests/bundle-metadata/dependencies.yaml

Installing KMM and KMM-Hub will now pull cert-manager as a dependency.

Make cert-manager an OLM dependency of KMM

---

api/v1beta1/module_webhook.go
api/v1beta1/module_webhook_test.go

When the `.spec.moduleLoader.container.version` field is set, the combined length of the name and namespace fields should not exceed 40 characters to avoid issues with labels.
Fixes #444 
/cc @yevgeny-shnaidman @mresvanis

Enforce name and namespace length in the webhook

---

controllers/pod_node_module_reconciler.go
controllers/pod_node_module_reconciler_test.go
internal/filter/filter.go
internal/filter/filter_test.go

ModuleLoader pods that have an empty `.spec.nodeName` cannot terminate properly because we filter out events for those objects and never remove their finalizer.
Modify the PodNodeModule reconciler so it removes the finalizer for those objects, as it should.
/cc @yevgeny-shnaidman @mresvanis

Do not require pods to have a `.spec.nodeName`

---

.github/actions/create-minikube-cluster/action.yml

Resolve  #450 
Update `.github/actions/create-minikube-cluster/action.yml` to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I found the workflow file that use `set-output` command through the following command:
```bash
$ find . -name '*.yml' -o -name '*.yaml' | xargs egrep '\bset-output\b'
```
**AS-IS**
```yaml
echo "::set-output name=version::$(minikube version --short)"
```
**TO-BE**
```yaml
echo "version=$(minikube version --short)" >> $GITHUB_OUTPUT
```

Replace deprecated command with environment file

---

CONTRIBUTING.md
Makefile
config/manifests-hub/bases/kernel-module-management-hub.clusterserviceversion.yaml
config/manifests/bases/kernel-module-management.clusterserviceversion.yaml
hack/release-operatorhub

Make a few adjustements to the base CSVs.
/cc @ybettan

Add a script generating files for OperatorHub.io

---

internal/daemonset/daemonset.go
internal/daemonset/daemonset_test.go

Quote arguments to avoid shell injections.

Quote arguments in modprobe commands

---

controllers/mock_module_reconciler.go
controllers/module_reconciler.go
controllers/module_reconciler_test.go
internal/daemonset/daemonset.go
internal/daemonset/daemonset_test.go

Currently in v1.1 the naming scheme for ModuleLoader and DevicePlugin daemonsets is different the what we had in v1.0.2. We are using hashings and the names are deterministic. This causes issues during upgrade, since the upgraded controller will try to create new daemonsets (new names). The old daemonsets can not be deleted, since it will cause the unloading of kernel modules. Since there is no way to change/delete lifecycle hooks of the running pod, we need to support the naming scheme of v1.0.2
The changes in PR:
1. get the runnings Daemonsets of the module in the earlier stage of the reconciliation loop
2. during ModuleLoader or DevicePlugin handling, check if the appropriate daemonset already exists based on the kernel-version and version label of daemonset
3. if now daemnonset is …

Upgrade support between v1.02 and v1.1

---

api/v1beta1/module_webhook.go
api/v1beta1/module_webhook_test.go

Prevent updating to or from an empty ModuleLoader version, as this requires recreating new DaemonSets because of labelSelector updates.

Add further checks on Module version

---

controllers/module_reconciler.go
internal/filter/filter.go
internal/filter/filter_test.go
internal/utils/nodeutils.go

Module controller needs to be scheduled in case node has been rebooted and becomes ready. Module controller get the target nodes for the modules based on the selector and the NonSchedulable taint of the node. Sometimes node's Ready condition is set while the taint is not being removed, which causes the reconcilation loop to skip DS generation, and we have not addition event  scheduled. This PR changes the condition for reconciliation kick-off: now we are waiting for node to become scheduled, instead of just ready

Fix race condition for Node reboot issue

---

cloudbuild.yaml

Build the worker image on each commit to `main`.
Fixes #471

Add Cloud Build configuration for the worker image

---

docs/mkdocs/documentation/deploy_kmod.md

Document default DaemonSet image pull policy

---

internal/module/kernelmapper.go
internal/module/kernelmapper_test.go

In case kernel mapping for the kernel version is not found, GetModuleLoaderDataForKernel API returns an indistinguishable error, just like in case there was some internal error during processing.
This PR introducing a new propriaetory error: ErrNotFound. In case kernel mapping for a specific kernel does not exists, this error will be returned. As a consequence, the calling code will be able to act seperatly on internal error, or on KernelMapping not present, which may not be an error at all

Adding NotFound error to the GetMLD API

---

controllers/nodemodulesconfig_reconciler.go
controllers/nodemodulesconfig_reconciler_test.go

The status of the working pod that has completed with error does not contain the valid Config field ( it is set only on success). When processing NMC, the NMC controller tries to compare the Config of the status and spec, and in that case it fails, since status Config is nil.
Fix: in case status != nil, inProgress = false and Config is nil, just create a loader worker pod, without futher comparison to the spec

Fixing panic in case worker pod has failed

---

internal/controllers/nmc_reconciler.go
internal/controllers/nmc_reconciler_test.go
internal/nmc/helper.go

This PR fixes 2 issues:
1) In case Load Pod is failing, its Config in status is nil.
if NMC is configured to un load the module, for whatever reason,
the code must also check if the Config is nil, and then just to
delete the status for module, in order to avoid panic
2) When unload Pod is failing, its status should be retained as is,
otherwise the Config is lost, and the following unload pod won't be
able to run

Fixing Unloading Kmod on a previously failed Load Pod

---

internal/controllers/nmc_reconciler.go
internal/controllers/nmc_reconciler_test.go

We need to call newPodManager function in roder to correctly initialize pullSecrets implementator, instead fo initializing workerHelperImpl explicitly

Fixing panic for pull secret implementation

---

Dockerfile.worker

On initiliazation, worker pod goes over /var/run/kmm/pull-secrets directory in roder to read all pull secret and create authentication keychain. Currently, in case no pullsecrets are define, this function fails, since the directory itself does not exists. This PR defines the directory in the Dockerfile, and during pod creation, pull secrets will be mapping via volumes

Fixing worker pod failure in case no pullsecrets are defined

---

Dockerfile
Dockerfile.worker
cmd/manager/main.go
config/manager-base/manager.yaml
internal/config/config.go
internal/config/config_test.go
internal/config/testdata/config.yaml
internal/controllers/nmc_reconciler.go
internal/controllers/nmc_reconciler_test.go

Create UID & GID 201 for the worker image, and use it by default.
Move the `manager` and `worker` binaries under `/usr/local/bin`.
Remove redundant `USER 65532:65532` from the manager Dockerfile.

Make all binaries run as regular users

---

.github/workflows/e2e.yaml
ci/install-ci-spoke/kustomization.yaml
ci/install-ci/kustomization.yaml
config/manager/controller_manager_config.yaml
config/rbac/role.yaml
internal/controllers/nmc_reconciler.go
internal/nmc/helper.go
internal/nmc/helper_test.go

Using `default` instead of an empty string allows us to attach all pull secrets configured for that account when setting up the mounts for the worker Pod.

Use the `default` ServiceAccount when creating NMC

---

internal/utils/podhelper.go
internal/utils/podhelper_test.go

Currently, PodPending phase of a running pod is not explicitly checked, which may cause an unnecessary errors reported. It does not affect the correctness of the flow, but does causes confusion in logs

Explicitly checking PodPending when reporting Build/Sign status

---

docs.mk

Download from GitHub as Sourceforge seems to suffer from lower reliability.

Update plantuml.jar download version and link

---

internal/controllers/module_nmc_reconciler.go
internal/controllers/module_nmc_reconciler_test.go
internal/utils/kmmlabels.go

Current implementation involves creating a daemonset per module version, and setting ModuleLoader/DevicePlugin labels for the version value into the Daemosets selector fields. NodeLabelModuleVersion controller adds/removes appropriate labels from nodes based on customer input.
In V2, device plugin ordered upgrade implmentation will remain the same. For kernel modules, module-nmc reconciler will decide how to change NMCs based on the labels' changes of the nodes (provided by NodeLabelModuleVersion controler).
Module-NMC will use the following decicion-making table to update NCM: 
1) if module is targeting the node, but kernel is not suitable - delete
from NMC
2) if module is targeting the node, but the version is missing from
Module (not an ordered upgrade) - add to NMC
3) if module is …

Implementing ordered upgrade feature for V2

---

internal/controllers/module_reconciler.go
internal/controllers/module_reconciler_test.go
internal/daemonset/daemonset.go
internal/daemonset/daemonset_test.go
internal/daemonset/mock_daemonset.go

KMM V2 does not contain Daemonset for ModuleLoader anymore, only for DevicePlugin. This PR changes implementatio n of GarbageCollector function in daemonset package and the appropriate unit-tests. The changes for the GC function include:
1) no need to handle Module Loader daemonsets, including Module Version
use case
2) no need verifying kernel versions of the nodes, which means changes
to the GC function input parameters

Changing daemonsets GarbageCollector for v2

---

api/v1beta1/module_webhook_test.go
internal/constants/constants.go
internal/controllers/mock_node_label_module_version_reconciler.go
internal/controllers/module_nmc_reconciler.go
internal/controllers/module_nmc_reconciler_test.go
internal/controllers/module_reconciler.go
internal/controllers/module_reconciler_test.go
internal/controllers/module_version_label_action_table.go
internal/controllers/node_label_module_version_reconciler.go
internal/controllers/node_label_module_version_reconciler_test.go
internal/utils/kmmlabels.go
internal/utils/kmmlabels_test.go

Main points:
1) Renaming the ordered upgrade internal label from module-loader to
worker-pod
2) simplifying labels reconciliation: no more need to check if
module-loader pod exists, now we only need to check device-plugin
pods
3) unit tests adaptation

Continuing adaption of ordered upgrade to KMM V2

---

ci/prow/e2e-incluster-build
internal/controllers/mock_nmc_reconciler.go
internal/controllers/module_nmc_reconciler.go
internal/controllers/module_nmc_reconciler_test.go
internal/controllers/nmc_reconciler.go
internal/controllers/nmc_reconciler_test.go
internal/filter/filter.go
internal/filter/filter_test.go
internal/filter/suite_test.go
internal/labels/labels.go
internal/labels/labels_test.go
internal/labels/suite_test.go
internal/nmc/helper.go
internal/nmc/helper_test.go
internal/nmc/labels.go
internal/nmc/labels_test.go
internal/utils/kmmlabels.go

Wait for kmods to be unloaded on all nodes to delete a `Module`.
This is implemented through 2 labels:
- `beta.kmm.node.kubernetes.io/<ns>.<name>.module-configured`
- `beta.kmm.node.kubernetes.io/<ns>.<name>.module-in-use`
Both labels are set by the Module-NMC reconciler when an entry is added to the NMC spec.
The first label is removed by the Module-NMC reconciler when, for any reason, the NMC is not targeted by the Module anymore.
The second label is removed by the NMC reconciler when the unloading worker pod is successful and the kmod is not present in the spec list anymore.
For the Module finalizer to be removed, no NMC must carry neither of these 2 labels.
/cc @yevgeny-shnaidman @mresvanis

Finalize Module resources

---

Dockerfile.kmm-operator-build
internal/controllers/mock_nmc_reconciler.go
internal/controllers/nmc_reconciler.go
internal/controllers/nmc_reconciler_test.go
internal/utils/kmmlabels.go

This PR adds the ability to add/remove
kmm.node.kubernetes.io/%s.%s.ready label to the node. This is done based on the current labels on the node, and the comparison between NMC module's spec and status. State machine for adding/removing:
1. if spec config and status config are not equal - node's label should stay as is (either present or missing)
2. if both spec and status are missing - node's label should be removed
3. if spec config and status config are equal - node's label should be set

Handling of kmm  module ready label (kernel module is loaded)

---

internal/cache/cache_test.go

This flaky internal cache test's root cause was that the `StartCollecting` method was locking the map to delete the expired item, but the respective test code could be writing to the map at the same time without locking it. By running the `StartCollecting` after the initial writing of the items to the map, we get rid of the possibility of `concurrent map read and write` errors.
Fixes #528

Fix concurrent map read and write in cache test

---

internal/cache/cache_test.go

This change leverages gomega's [Eventually](https://pkg.go.dev/github.com/onsi/gomega#Eventually) to wait until the expired cache key has been removed or a timeout occurs.
> Eventually's default timeout is 1s and its default polling interval is 10ms

Fix flaky async cache test

---

internal/controllers/nmc_reconciler.go
internal/controllers/nmc_reconciler_test.go

Restart failed worker Pods using the usual backoff mechanism.

Allow worker pods to restart on failures

---

internal/controllers/mock_module_reconciler.go
internal/controllers/module_reconciler.go
internal/controllers/module_reconciler_test.go

Currently, when the module is deleted, the finalization function is called. This function basically waits till all the kernel modules has been unloaded, and only then removes the finalizer from Module. In case device-plugin is deployed, its Daemonset won't be deleted (since Module is not deleted due to finalizer), and the kernel modules cannot be unloaded due to device plugin running
Solution: in case of Module being deleted, handle device-plugin deletion in the module-reconciler specifically, and not wait for it to be deleted based on ownerReference

Fixing Module with device-plugin finalization deadlock

---

internal/controllers/mock_node_label_module_version_reconciler.go
internal/controllers/node_label_module_version_reconciler.go
internal/controllers/node_label_module_version_reconciler_test.go

This PR inforces the correct ordering of add/removing version labels for worker pods and device-plugin. The correct sequence should always be:
1. remove old version device-plugin label (if exists)
2. remove old version worker pod label (only in case no relevant device-plugin pod is present)
3. add new version worker pod label (only in case the kernel module is not loaded)
4. add new version device-plugin label ( if needed)
We are stalling for worker-pod labels in order to make sure that new device-label pod will not be scheduled prior to new version of kernel module being loaded. Otherwise, old version will never be able to be removed from the kernel

Fix device-plugin/worker pod labels validationsduring ordered-upgrade

---

ci/module-kmm-ci-build-sign.yaml
ci/prow/e2e-incluster-build

Use `kmm_ci_b` which is already built in the kmm-kmod image.
Fixes #477
/cc @yevgeny-shnaidman @ybettan

Test the soft dependencies feature in CI

---

cmd/worker/funcs_kmod.go
cmd/worker/funcs_kmod_test.go
cmd/worker/main.go
go.mod
go.sum
internal/controllers/nmc_reconciler.go
internal/controllers/nmc_reconciler_test.go
internal/worker/constants.go
internal/worker/mock_worker.go
internal/worker/worker.go
internal/worker/worker_test.go

1) mapping of the host firmware directory into the load/unload pod only
in case firmware for the Module is defined
2) during Loading operation, worker pod is copying all firmware files and
directories from image onto the mapped host directory
3) during Unloading operation, worker pod is deleting all firmware
files, but not directories ( since those can be shared with other
modules' firmware files
4) unit tests

Adding support for firmware loading

---

internal/controllers/nmc_reconciler.go
internal/controllers/nmc_reconciler_test.go

We need to revert the restart policy from RestartOnFailure to Never. In case restart policy is RestartOnFailure, the Phase of the Pod will always be Running and never Failed. This in turn causes 2 things:
1. even when the Module is removed from NMC Spec, NMC status is always in Progress, and Moduke is never removed from NMC Status. This means that in-use label never removed and Module deletion is never successfully finilized
2. in case Pod fails, and the NMC spec is updated, the new Pod is never created, since the old pod is InProgress

Reverting RestartPolicy back to Never

---

ci/module-kmm-ci-build-sign.yaml
ci/prow/e2e-incluster-build

Load the `dummy` module to have it unloaded by the KMM worker before loading `kmm_ci`.
/cc @yevgeny-shnaidman @ybettan

Test the in-tree removal feature

---

internal/controllers/nmc_reconciler.go
internal/controllers/nmc_reconciler_test.go

First bug:
If during module deletion scenario, UnloadKmod function returns and error for some reason, the GarbageCollectInUseLabels and UpdateNodeLabelsAndRecordEvents onw't be called. This in turn means, that if there is a module that was being loaded/unloaded in parallel, the actual action will happen (load/unload from kernel), but the label in NMC and node won't be updated.
Solution: always continue with GarbageCollectInUseLabels and UpdateNodeLabelsAndRecordEvents and return a collective error later
Second bug:
In case ProcessModuleSpec from some spec/status has failed, the status would not be deleted from the statusMap, which will cause it later to be treated as orphaned status and the UnloadKmod to be called. Solution: always delete status from statusMap, even in case of a failure

Fixing 2 bugs related to failure scenarios

---

internal/controllers/device_plugin_reconciler.go
internal/controllers/device_plugin_reconciler_test.go
internal/controllers/mock_module_nmc_reconciler.go
internal/controllers/module_nmc_reconciler.go
internal/controllers/module_nmc_reconciler_test.go

This commits adds implementation of reporting device plugin status into the Module's status.
The following fields are reported:
1) number of targeted nodes ( based on selector field) 2) number of desired podsto be run
3) current number of the pods actually running

adapting Device Plugin status report in Module to v.2

---

api/v1beta1/module_webhook.go
api/v1beta1/module_webhook_test.go

Currently webhook verifies that module's name + namespace length does not exceed 40 chars in case version is defined. This commit removes the version condition and always verifies that length

Update webhook validation for name+namespace length

---

internal/controllers/nmc_reconciler.go
internal/controllers/nmc_reconciler_test.go

Since the name of the volumes and volume mounts that are configured for service-account pull-secrets are constructed from "pull-secret" and the actual pull-secret name, then it can result in names being more then 63 chars which will cause an error. This comment move the volumes names to be "pull-secret-hash(pull-secret-name)"

Restructure Worker Pod secrets' volumes' names

---

api/v1beta1/module_webhook.go
api/v1beta1/module_webhook_test.go

Currently webhook verifies that module's name + namespace length does not exceed 40 chars in case version is defined. This commit removes the version condition and always verifies that length

Update webhook validation for name+namespace length (#607)

---

internal/controllers/device_plugin_reconciler.go
internal/controllers/device_plugin_reconciler_test.go
internal/controllers/mock_module_nmc_reconciler.go
internal/controllers/module_nmc_reconciler.go
internal/controllers/module_nmc_reconciler_test.go
internal/nmc/helper.go
internal/nmc/helper_test.go
internal/nmc/mock_helper.go

This commits adds implementation of reporting worker pods status into the Module's status.
The following fields are reported:
1) number of targeted nodes ( based on selector field)
2) number of desired nodes that kernel module should be deployed (based
on NMCs configured)
3) current number of the nodes that the kernel module is already
deployed to ( based on NMC spec and status configs)

adapting Worker Pods status report in Module to v.2 (#619)

---

config/manager-base/manager.yaml

[release-2.0] Bump memory limit to 384Mi

---

hack/release-operatorhub

operator-sdk now sets that field for us.
Make new environment variables for the signer and worker image names mandatory.

Do not set `createdAt` manually in the CSV

---

hack/release-operatorhub

operator-sdk now sets that field for us.
Make new environment variables for the signer and worker image names mandatory.
---
This is a cherry-pick of da759a0.

[release-2.0] Do not set `createdAt` manually in the CSV

---

config/rbac/role.yaml
internal/controllers/module_nmc_reconciler.go

Make the OwnerReferencesPermissionEnforcement admission plugin happy.

Allow the controller to delete NodeModulesConfigs

---

docs/mkdocs/documentation/ordered_upgrade.md

Update ordered upgrade docs for v2

---

docs/mkdocs/developer/use_cases.md

`const` [`ModuleNameLabel      = "kmm.node.kubernetes.io/module.name"`](https://github.com/kubernetes-sigs/kernel-module-management/blob/940e25e11ed701e6c218577066e29cadb4d9a62d/internal/constants/constants.go#L4).

Docs typo - Use Cases - `module.name` not `module-name`

---

internal/controllers/nmc_reconciler.go
internal/controllers/nmc_reconciler_test.go
internal/utils/kmmlabels.go
internal/utils/kmmlabels_test.go

This change removes `kmm.node.kubernetes.io/<module>.ready` labels on all nodes, as it was deprecated in v1.1 and removed in v2.0.

Remove deprecated module ready labels on nodes

---

internal/controllers/module_nmc_reconciler.go
internal/controllers/module_nmc_reconciler_test.go

Fix scheduling data generation for nodes that run an unconfigured kernel and do not have the kmod loaded yet.

Fix handling of unknown kernels

---

Dockerfile.kmm-operator-build
pkg/labels/labels.go
pkg/labels/labels_test.go
pkg/labels/suite_test.go

since "ready" labels are public APIs of KMM, operators using KMM may want to schedule they workloads based on the presence of those labels.

Making GetModuleReady/GetDevicePluginReadyLabels functions public

---

internal/constants/constants.go
internal/controllers/device_plugin_reconciler.go
internal/controllers/device_plugin_reconciler_test.go

In v1.x we had 2 type of Daemonsets: DevicePlugin and ModuleLoader, which could be distingished by the DaemonsetRole label In v2.x, there only 1 type of daemonset, DevicePlugin, so the DaemonsetRole labels was removed.
During DevicePlugin reconciliation, reconcile get all the device plugin Ds based only on module name label, which means that in case there is a v1.1 ModuleLoader DS running it will also be chosen. Once reconciler tries to reconcile ModuleLoader DS, it will fail
This PR, updates the function that chooses the DevicePlugin DS, by removing old ModuleLoader Ds based on Role label

Fixing DevicePlugin upgrade from v1.x to v2.x

---

config/manager-base/manager.yaml
docs/mkdocs/lab/index.md

Add extra label `kmm.node.kubernetes.io/control-plane`  to `nodeSelectorTerms` so KMM controller can be installed at worker nodes in certain scenarios, i.e. EKS or other clusters where master nodes do not allow user workloads.
https://github.com/kubernetes-sigs/kernel-module-management/issues/666

Add extra label for controllers to install at worker nodes

---

config/manager/controller_config.yaml
docs/mkdocs.yml
docs/mkdocs/documentation/configure.md
docs/mkdocs/documentation/deploy_kmod.md
docs/mkdocs/documentation/firmwares.md
docs/mkdocs/documentation/hub_spoke.md
docs/mkdocs/documentation/install.md
docs/mkdocs/documentation/troubleshooting.md

Add a reference page for the operator configuration.
Mention that OperatorHub.io installation methods install in the `operators` namespace.

Update docs to v2.0.1

---

.github/workflows/e2e.yaml
ci/prow/operator-upgrade

This test will ensure the bundle built in the PR can be used to upgrade
from the last bundle available of KMM.
---
Fixes https://github.com/kubernetes-sigs/kernel-module-management/issues/478

Adding an operator-upgrade Github workflow.

---

.github/workflows/e2e.yaml

Reverts kubernetes-sigs/kernel-module-management#706
--- 
We should revert this PR in order to be able to revert https://github.com/kubernetes-sigs/kernel-module-management/pull/693

Revert "Bump actions/cache from 3 to 4"

---

config/rbac-hub/role.yaml
internal/controllers/hub/managedclustermodule_reconciler.go

This is required for the `BuildSignEvents` reconciler to remove the finalizer.
/cc @mresvanis @yevgeny-shnaidman

Allow the Hub to patch pods

---

Makefile

`hack/release-operatorhub` now needs the `WORKER_IMG` and `SIGNER_IMG` environment variables.
/cc @mresvanis

`make operatorhub-release`: bind all environment variables

---

docs/mkdocs/documentation/kmod_image.md

Fixes #517
@hershpa could you please have a look at this and let me know if this is clear enough? Thanks!
/cc @mresvanis

Document symlinks for in-tree dependencies

---

api-hub/v1beta1/managedclustermodule_types.go
api/v1beta1/module_types.go
config/crd-hub/bases/hub.kmm.sigs.x-k8s.io_managedclustermodules.yaml
config/crd/bases/kmm.sigs.x-k8s.io_modules.yaml
config/crd/bases/kmm.sigs.x-k8s.io_nodemodulesconfigs.yaml

`Module`: make moduleName an optional field.
`ManagedClusterModule`: make spokeNamespace a required field.
/cc @mresvanis

Make slight changes to the CRDs

---

.github/workflows/e2e.yaml
ci/prow/operator-upgrade

The latest published bundle for our cluster is available in the `operatorhubio-catalog` service in the `olm` namespace, therefore, there is no need to rebuild it.
---
Fixes https://github.com/kubernetes-sigs/kernel-module-management/issues/756

Getting the last published bundles from OLM instead of building it.

---

Makefile
config/crd-hub/patches/webhook_in_managedclustermodules.yaml
config/crd/patches/webhook_in_modules.yaml
config/crd/patches/webhook_in_preflightvalidations.yaml
config/default-hub/kustomization.yaml
config/default/kustomization.yaml
config/webhook-hub/kustomization.yaml
config/webhook-hub/service.yaml
config/webhook/kustomization.yaml
config/webhook/service.yaml

controller-gen generates webhook configuration targeting `webhook-service`.
Unfortunately OLM requires that the webhook Service be named `${DEPLOYMENT_NAME}-service`, so `webhook-server-service`. Not following that requirement results in duplicate Services being created, and sometimes in TLS issues.
Rename the webhook service to `webhook-server-service` and add a kustomize replacement rule to modify the target service for webhooks.
/cc @mresvanis @yevgeny-shnaidman @ybettan

Rename the webhook service

---

api/v1beta1/preflightvalidation_types.go
api/v1beta1/preflightvalidation_types_test.go

Also populate old-style, un-namespaced status keys to remain compatible with clients designed for pre-2.1 KMM.

`PreflightValidation`: populate old status keys

---

cmd/manager-hub/main.go
cmd/manager/main.go
internal/build/manager.go
internal/build/mock_manager.go
internal/build/pod/maker.go
internal/build/pod/maker_test.go
internal/build/pod/manager.go
internal/build/pod/manager_test.go
internal/cluster/cluster.go
internal/cluster/cluster_test.go
internal/config/config.go
internal/config/config_test.go
internal/config/testdata/config.yaml
internal/constants/constants.go
internal/controllers/build_sign_reconciler.go
internal/controllers/build_sign_reconciler_test.go
internal/controllers/mock_build_sign_reconciler.go
internal/sign/manager.go
internal/sign/mock_manager.go
internal/sign/pod/manager.go
internal/sign/pod/manager_test.go
internal/sign/pod/signer.go
internal/sign/pod/signer_test.go
internal/utils/mock_podhelper.go
internal/utils/podhelper.go

Add the `job.gcDelay` operator configuration property to delay the garbage collection of successful build and signing jobs.
Add the new `kmm.node.kubernetes.io/gc-delay finalizer` to all new jobs.
Only clear the finalizer after `deletionTimestamp+gcDelay`.
Fixes #572
/cc @yevgeny-shnaidman @mresvanis @ybettan

Optionally delay job garbage collection

---

.github/workflows/codeql-analysis.yml
cloudbuild.yaml

Use Go 1.22 in Google Cloud Build and a CI job.
/cc @mresvanis

Update the Go version in more places

---

internal/api/moduleloaderdata.go
internal/build/pod/maker.go
internal/build/pod/maker_test.go
internal/build/pod/manager.go
internal/build/pod/manager_test.go
internal/kernel/kernel.go
internal/kernel/kernel_test.go
internal/kernel/suite_test.go
internal/module/kernelmapper.go
internal/module/kernelmapper_test.go
internal/sign/helper.go
internal/sign/pod/manager.go
internal/sign/pod/manager_test.go

Handle uncommon kernel versions with characters such as `+`, by replacing them with `_`.
/cc @ybettan @mresvanis

Normalize kernel version in labels and image tags

---

internal/node/node_test.go

Some of the functions in the `node` package do not have any unit tests. 
This commit adds new unit tests for them.
---
This PR adds unit tests to the functions in the `node` package:
1. `IsNodeSchedulable`
2. `GetNumTargetedNodes`
3. `FindNodeCondition`

adding unit tests to `node` package

---

internal/registry/registry.go
internal/registry/registry_test.go
internal/webhook/module.go
internal/webhook/module_test.go

In the current code, we handle differently build/sign and deploying a pre-built kmod.
This is the current behavior:
* If a `build`/`sign` section is set in the module, and the image tag isn't specified, then we will return an error.
* If there are no `build`/`sign` section, and the image tag isn't specified, then we will default to the `latest` tag.
This change is adjusting the behavior of both workflow to enforce the customer to explicitely set a sha or a tag in his container image.
---
/cc @yevgeny-shnaidman @TomerNewman 
This PR is replacing https://github.com/kubernetes-sigs/kernel-module-management/pull/826 due to its difficulties.

Refusing `Modules` with container images without a sha or a tag.

---

internal/controllers/mock_nmc_reconciler.go
internal/controllers/nmc_reconciler.go
internal/controllers/nmc_reconciler_test.go
internal/node/mock_node.go
internal/node/node.go
internal/node/node_test.go

Today, the UpdateNodeLabelsAndRecordEvents function has around 100 lines of code. This commit aims to enhance its readability and maintainability by using helper functions, thereby reducing its total length. Additionally, adding unit tests that covers the new helper functions.

Shorten UpdateNodeLabelsAndRecordEvents function in nmc_reconciler.go

---

internal/controllers/nmc_reconciler.go
internal/controllers/nmc_reconciler_test.go

Until now, the test for `Reconcile` function in _nmc_reconciler.go_ only checked that the errors were not nil. Now, the test will ensure that the returned errors match the expected errors exactly.

Update Reconcile Test to Validate Specific Errors

---

config/manager-base/manager.yaml
config/webhook-server/deployment.yaml

For the KMM operator, the `ImagePullPolicy` was set to `Always` for development reasons but it is in fact not the best practice, therefore, it was removed to allowed `kubelet` to have its default pull policy.
The webhook-server's pull policy was also removed to use the default behavior to stay in sync with the KMM operator it is deployed with.
In a nutshell, the default policy is `Always` if the `latest` tag is used and `IfNotPresent` otherwise.
This change is expected to reduce the networking bandwidth.
---
/cc @yevgeny-shnaidman @TomerNewman

Changing the `ImagePullPolicy` for the operator and the webhook.

---

config/manager/controller_config.yaml
docs/mkdocs/documentation/configure.md
docs/mkdocs/documentation/deploy_kmod.md
docs/mkdocs/documentation/firmwares.md
internal/controllers/nmc_reconciler.go
internal/controllers/nmc_reconciler_test.go
internal/worker/constants.go

When firmware is added to the driver-cotnainer there are 2 actions that were taken:
1. Copy the firmware files onto the node at `/var/lib/firmware`
2. Add `/var/lib/firmware` to `/sys/module/firmware_class/parameters/path` in order to update the kernel lookup directories for firmware files.
In order to make this feature configurable, we will allow the user to choose the path on the nodes to write the firmware files to.
In order to make it work with no additional changes, when firmware files are added to the driver-container, we added a default directory to add the firmware files to on the nodes.
To keep it simple, we will also always add this path to the kernel lookup directories.
---
unit-tests are still failing but the code should stay the same.

Set a default value for `setFirmwareClassPath` in the worker config.

---

config/manager/controller_config.yaml
internal/config/config.go
internal/config/config_test.go
internal/config/testdata/config.yaml
internal/controllers/nmc_reconciler.go
internal/controllers/nmc_reconciler_test.go

1) changing the setFirmwareClassPath flag to firmwareHostPath flag. This
flag is used to:
a) define the firmware path on the host
b) define the mount point on the worker pod
c) define the new firmware search path in the Linux kernel
2) updating NMC controller code to use the new flag for setting firmware
volume for worker pods and passing parameters to worker pod
entrypoint
3) updating unit-test

Changing the FirmwarePath config flag

---

cmd/worker/funcs_kmod.go
cmd/worker/funcs_kmod_test.go
internal/controllers/nmc_reconciler.go
internal/controllers/nmc_reconciler_test.go
internal/worker/constants.go

Currently NMC controller passes 2 flag to worker pod: firmware path mount point in pod and firmware search path. Since in our implementation those 2 values are always equal, we can use only one flag to pass these values: --firmware-path, and let worker pod decide when to update the kernel configuration for firmware search

Simplifying firmware flags between NMC controller and worker pod

---

config/default-hub/kustomizeconfig.yaml
config/default/kustomizeconfig.yaml
config/webhook-cert/kustomizeconfig.yaml
hack/download-kustomize

Since `kustomize@v5.4.0`, `yaml.UnmarshalStric()` is used instead of `yaml.Unmarshal()` which means that fields in the yamls that doesn't exist in the golang object will fail to unmarshal instead of being ignored like they would without the `strict` behavior.
Therefore, those redundant `name` fields where removed.
In addition, I have bumped `kustomize@5.3.0` --> `kustomize@5.4.3` to make sure we get a closer behavior on machines that comes with `kustomize` pre-installed and those which aren't and install it on-the-fly.
--
This PR is blocking a bunch of other PRs like:
* https://github.com/kubernetes-sigs/kernel-module-management/pull/886
* https://github.com/kubernetes-sigs/kernel-module-management/pull/882
* …

Fixing some `kustomizeconfig.yaml` files.

---

.github/workflows/e2e.yaml
internal/controllers/nmc_reconciler.go
internal/controllers/nmc_reconciler_test.go
internal/worker/worker.go
internal/worker/worker_test.go

This init container will be pulled by the container-runtime of the cluster and will copy all `.ko` and firmware files to a shared volume accessible by the worker container to load.
---
/hold
Didn't test it e2e yet.

Adding an init container to the worker pod.

---

api/v1beta1/nodemodulesconfig_types.go
config/crd/bases/kmm.sigs.x-k8s.io_nodemodulesconfigs.yaml
internal/controllers/module_nmc_reconciler.go
internal/controllers/nmc_reconciler.go
internal/controllers/nmc_reconciler_test.go

When we moved to the worker-pod implementation in v2 we started to pull kmod images via HTTP from teh worker-pod directly and we ignored this field.
Now that we moved to pulling using the cluster's container-runtime, the `imagePullPolicy` can be passed to the init-container definition.
---

Using the Module's `spec.moduleLoader.container.imagePullPolicy`.

---

internal/controllers/nmc_reconciler.go
internal/controllers/nmc_reconciler_test.go
internal/node/mock_node.go
internal/node/node.go
internal/node/node_test.go

This PR is a preparation for the fixes needed for cluster upgrade KMM implementation. We are adding a new function to the node interface, that determines whether a node has been rebooted while a kernel module was loaded. This PR also updates NMC controller to use this API and refactors the unit-test

Changing Node interface and updating NMC controller

---

internal/controllers/mock_nmc_reconciler.go
internal/controllers/nmc_reconciler.go
internal/controllers/nmc_reconciler_test.go

The following scenario causes worker pods to be stuck during cluster upgrade:
1) kernel module is loaded into the node. NMC contains both spec and
status using the current kernel version
2) cluster upgrade starts. As part of the upgrade node becomes
Unschedulable
3) Module-NMC removes Spec from NMC, since the node is Uschedulable 4) Node becomes schedulable
5) NMC controller tries to unload kernel module using the NMC Status
confiration, which contains old kernel.
6) Worker unload pods get stuck in Error, since Node is running the new
kernel
7) Module-NMC updates Spec of NMC, but since worker pod exists, nothing
is done
Solution:
When processing orphaned NMC statuses (status exists but spec does
not), NMC controller should ignore modules that have statuses created prior to Node's Ready …

Fixing race condition during cluster upgrade with kernel upgrade

---

internal/controllers/nmc_reconciler.go
internal/controllers/nmc_reconciler_test.go

The following scenario causes worker pods to be stuck during cluster upgrade:
1) kernel module is loaded into the node. NMC contains both spec and status using the current kernel version 2) cluster upgrade starts. As part of the upgrade node becomes
Unschedulable
3) Module-NMC removes Spec from NMC, since the node is Uschedulable 4) NMC controller creates an unload worker pod, since the timestamp of
the ready condition of the node has not been updated yet to a new
value (the node is still not ready).
5) once the node becomes ready, the unload worker pod is scheduled with
the old kernel version and therefore constantly fails.
Solution:
We will skip handling spec, statuses , garbage collection and labelling for the node that are not ready (unschedulable). We will only collect the completed …

Fixing yet another race condition during cluster/kernel upgrade

---

docs/enhancements/0002-container-runtime.md

---
/cc @yevgeny-shnaidman @mresvanis @TomerNewman

Adding an enhancement for checking image existence using the container-runtime.

---

docs/enhancements/0003-module-nmc-responsibilty-refactoring.md

Enhancement for redefining communication between Module-NMC and NMC

---

internal/controllers/nmc_reconciler.go
internal/controllers/nmc_reconciler_test.go

image repo secret wasd previously extracted from the volume that was mapped into the loading pod. Since the volume no longer exists, we must extract it from the imagePullSecret of the loading pod

Fixing image repo secret extraction for unloading worker pod

---

internal/controllers/nmc_reconciler.go
internal/controllers/nmc_reconciler_test.go
internal/node/mock_node.go
internal/node/node.go
internal/node/node_test.go

Until now, nodes retained their kmod labels even when they became NotReady for any reason (e.g., a reboot).
Today, we are removing these labels when a node is NotReady to address a potential race condition.
---
Besides updating the unit tests, I also tested this manually with simple-kmod, and it works as expected (label was deleted when Node became NotReady).
---
I am also checking whether to remove the label using `IsDeprecatedKernelModuleReadyNodeLabel`. If this is not relevant, please let me know, and I will update it accordingly.
/cc @yevgeny-shnaidman @ybettan

Removing labels when node NotReady

---

internal/controllers/nmc_reconciler.go
internal/controllers/nmc_reconciler_test.go
internal/node/mock_node.go
internal/node/node.go
internal/node/node_test.go

This change addresses #940.
Kmod labels are now deleted only if the kernel module does not have the appropriate tolerations for the taints on the node.
---
/cc @yevgeny-shnaidman  @ybettan

Removing kmod labels without appropriate tolerations

---

api/v1beta1/nodemodulesconfig_types.go
config/crd/bases/kmm.sigs.x-k8s.io_nodemodulesconfigs.yaml

Currently ImagePullPolicy has a kubebuilder instruction for default value, which automatically makes it a required field. In previous version, this field was optional, meaning: when upgrading KMM operator, the upgrade will fail , since NMC object will be missing the required field
This commit keep the default value, but makes this field optional, in order to solve the upgrade issue

Making ImagePullPolicy in NMC optional

---

ci/install-ci-hub/kustomization.yaml
ci/install-ci/kustomization.yaml
ci/prow/e2e-hub-spoke-incluster-build
ci/prow/e2e-incluster-build
ci/prow/operator-upgrade
config/deploy-hub/kustomization.yaml
config/deploy/kustomization.yaml
config/webhook-cert/kustomization.yaml
config/webhook-server/deployment.yaml
docs/mkdocs/documentation/troubleshooting.md

* When we generate files with `controller-gen` it generates a service called `webhook-service` and it is not configurable.
* When we deploy KMM with OLM, OLM deploys a service for the webhook called `<webhook-deployment-name>-service`.
Therefore, before this change, we were getting 2 services for the same deployment. One generated by `controller-gen` and added to the bundle manifests and the other one created "on the fly" by OLM.
This change will make OLM find an already existing service called `webhook-service` in the cluster because the deployment is called `webhook`, therefore, it won't create a second service as before.
Services in KMM's namespace before the changes:
```
kmm-operator-controller-metrics-service   ClusterIP   10.129.169.25   <none>  8443/TCP   2d2h …
```

Renaming the webhook deployment from `webhook-server` to `webhook`.

---

ci/prow/e2e-hub-spoke-incluster-build
ci/prow/e2e-incluster-build

The webhook services are not always available right after the deployments are ready. This is causing a race condition between the services being ready to get requests and the CRs applied to the cluster.
By retrying to apply the CRs we can give the services the time they need to become ready.
---
/cc @TomerNewman 
It is supposed to solve all those endless retry of the e2e jobs because of errors such as:
```
Error from server (InternalError): error when creating "ci/managedclustermodule-kmm-ci-build-sign.yaml": Internal error occurred: failed calling webhook "vmanagedclustermodule.kb.io": failed to call webhook: Post "[https://kmm-operator-hub-webhook-service.kmm-operator-system.svc:443/validate-hub-kmm-sigs-x-k8s-io-v1beta1-managedclustermodule?timeout=10s](https …
```

Retrying applying CRs in the `e2e` jobs.

---

internal/nmc/labels.go
internal/nmc/labels_test.go

When a `Module` is deleted, the `NMC` controller is removing the labels for this `Module` in the `NMC` object.
As long as those labels for a specific module exists, the module's finalizer will not be removed upon module deletion and the module will keep hanging forever if deleted.
When a module is created with a `.` in its name, the created label for `NMC` doesn't match the expected regexp for this label and, therefore, not removed upon module's deletion.
Adding the `.` will allow the label to match the regexp, be removed upon deletion and deleting the module gracefully.
---
/cc @TomerNewman 
Fixes https://github.com/kubernetes-sigs/kernel-module-management/issues/967

Adding a `.` as a valid character for `Module`s' name.

---

Makefile

We are pretty often hitting a timeout waiting for the `cert-manager-webhook` deployment which becomes ready after the failure.
Timeout is now increased to give enough time for the webhook to be deployed.
---
Here is a [failing job example](https://github.com/kubernetes-sigs/kernel-module-management/actions/runs/12860299514/job/35852064202?pr=977).

Increasing the timeout for `cert-manager` deployments.

---

api/v1beta1/moduleimagesconfig_types.go
config/crd/bases/kmm.sigs.x-k8s.io_modulebuildsignconfig.yaml
config/crd/bases/kmm.sigs.x-k8s.io_moduleimagesconfigs.yaml

Removing generation and observed generation from Image Spec and Status. Adding new Regeneration field in the Spec which will be used for kicking off a new round of reconciliation.
If the image status is "does not exists, the reconcilaition can be re-triggered, even if no objects monitored by the reconciler have been changed (image pushed to repo, Build/Sign dockerfile changed, etc')

Changing the Generation and ObservedGeneration

---

api/v1beta1/modulebuildsignconfig_types.go
api/v1beta1/nodemodulesconfig_types.go
config/crd/bases/kmm.sigs.x-k8s.io_modulebuildsignconfigs.yaml
config/crd/kustomization.yaml

Those are new API objects that were recently introduced but were not added to the manifest files.
---

Adding `ModuleImagesConfig` and `ModuleBuildSignConfig` CRDs manifests.

---

internal/controllers/device_plugin_reconciler.go
internal/controllers/device_plugin_reconciler_test.go

Curently tolerations are applied only to worker pods, but not to the DevicePlugin pod. This PR adds the toleration definition from Module to the DevicePlugin's pod.

Adding tolerations specifications from Module to device plugin pods

---

api/v1beta1/moduleimagesconfig_types.go
config/crd/bases/kmm.sigs.x-k8s.io_modulebuildsignconfigs.yaml
config/crd/bases/kmm.sigs.x-k8s.io_moduleimagesconfigs.yaml

At first, we thought we will need a field to let the `MIC` future controller know that it needs to retry pulling an image that didn't exist, for example if the user has forgot to push the image.
We decided to just set the future pull pod with `restartPolicy=OnFailure` instead that will constantly retry to run the pod when it fails with an exp waiting time before retries and the max waiting time being 5m. If we wish to manually retry the pod without waiting the current waiting time, we can just delete the pull pod and the `MIC` controller will re-create it instantly.
It removed the need for maintaining a `Generation` field separately.
---

Removing the `Generation` field from the `ModuleImagesConfigSpec`.

---

cmd/manager/main.go
config/rbac/role.yaml
internal/controllers/mock_module_reconciler.go
internal/controllers/module_reconciler.go
internal/controllers/module_reconciler_test.go
internal/filter/filter.go

The `Module` reconciler will now generate and update
`ModuleImagesConfig`s objects in the cluster.
At this point, those objects aren't reconciled by any controller but
they will in the upcoming commits. For this reason, the `Module` controller
isn't checking the `MIC`'s status but instead keep checking if images exists
using direct HTTP calls.
---
Here is the `ModuleImagesConfig` created for a simple `Module` on a minikube cluster:
```
ybettan kernel-module-management (module-reconciler) $  oc get mic/kmm-ci -o yaml | yq
apiVersion: kmm.sigs.x-k8s.io/v1beta1
kind: ModuleImagesConfig
metadata:
creationTimestamp: "2025-02-06T14:19:13Z"
generation: 1
name: kmm-ci
namespace: default
ownerReferences:
- apiVersion: kmm.sigs.x-k8s.io/v1beta1
kind: Module
name: kmm-ci …
```

Generating `ModuleConfigImages` objects during `Module` reconciliation.

---

internal/mbsc/mbsc.go
internal/mbsc/mbsc_test.go
internal/mbsc/mock_mbsc.go

Adding GetImageSpec API which returns image spec in MBSC object based on the image name. Currently will be used by the MIC controller, but will probbably be used by MBSC controller also

Adding GetImageSpec API to the mbsc package

---

api/v1beta1/moduleimagesconfig_types.go
config/crd/bases/kmm.sigs.x-k8s.io_moduleimagesconfigs.yaml
internal/controllers/module_reconciler_test.go

Until now, when the node selectors were not match to any of the actual nodes, it still tried to create mic resource, even though we expect it to do nothing.
This commit allows to apply mic resources with an empty images field.
---
what we are getting is:
` "Reconciler error" err="failed to handle MIC: failed to apply default/example-module MIC: failed to create or patch default/example-module: ModuleImagesConfig.kmm.sigs.x-k8s.io \"example-module\" is invalid: spec.images: Required value" logger="kmm" controller="ModuleReconciler" controllerGroup="kmm.sigs.x-k8s.io" controllerKind="Module" Module="default/example-module" namespace="default" name="example-module" reconcileID="bbaed649-8ffe-4c36-a27d-442af70c3e3c"
`
over and over and over again
---

Creating mic resource also when images field is empty

---

api/v1beta1/moduleimagesconfig_types.go
config/crd/bases/kmm.sigs.x-k8s.io_modulebuildsignconfigs.yaml
config/crd/bases/kmm.sigs.x-k8s.io_moduleimagesconfigs.yaml
internal/controllers/module_reconciler.go
internal/controllers/module_reconciler_test.go

MIC image spec is being propgated as is to the MBSC image spec. As part of building sign and build pod, one of the inputs is the kernel version that this image is targeted for. This PR does the following:
1. Add KernelVersion field to the ModuleImageSpec
2. module reconciler sets the KernelVersion in the imageSpec variable
3. changing unit-tests

Adding KernelVersion to the MIC image spec

---

internal/controllers/nmc_reconciler.go
internal/controllers/nmc_reconciler_test.go
internal/pod/mock_workerpodmanager.go
internal/pod/workerpodmanager.go
internal/pod/workerpodmanager_test.go

When this interface was transitioned to the `pod` package, it was copied as is (as much as possible) and some variables had to be exported to be used as before.
Once the transition done, it was simpler to review some of those new exported env variables and convert them to usefull methods inside the `WorkerPodManager` interface.
---

Un-exporting some of `WorkerPodManager` interface env variables.

---

internal/mbsc/mbsc.go
internal/mbsc/mbsc_test.go
internal/mbsc/mock_mbsc.go

This API will be used by the mbsc controller to set the status of the image into the MBSC object

Adding SetImageStatus API to mbsc package

---

internal/pod/buildsignpodmanager.go
internal/pod/buildsignpodmanager_test.go

When defining constants for Status type, the type must also be defined, otherwise those value are of type string

Fixing buildsignpodmanager Status constants

---

cloudbuild.yaml

xref https://github.com/kubernetes/kubernetes/issues/130457
https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/post-kernel-module-management-push-images/1895046355202609152 
failed for 
> BUILD FAILURE: Build step failure: build step 10 "golang:1.22-alpine3.19" failed: step exited with non-zero status: 2
> ERROR: (gcloud.builds.submit) build 7[862](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/post-kernel-module-management-push-images/1895046355202609152#1:build-log.txt%3A862)5c53-80f3-4a19-a4ac-1c57bed63037 completed with status "FAILURE"
> Step #10 - "build-bundles": /workspace/bin/controller-gen crd paths="./api/..." output:crd:artifacts:config=config/crd/bases
> Step #10 - "build-bundles": Error: load packages in root "/workspace/api": err: exit status 1: stderr: go: ../go.mod …

bump build bundles to golang 1.23-alpine3.21

---

internal/buildsign/manager.go
internal/buildsign/mock_manager.go
internal/buildsign/pod/manager.go
internal/buildsign/pod/manager_test.go

Currently the GarbageCollector API receives the PodType as an input parameter. The PodType  is defined in the pod package, which should not be used by the callee, since it is a porting layer. This commit changes the API to use kmmv1beta1.BuildOrSignAction, and the translation to the PodType will be done inside the manager code

Changing the GarbageCollector API of the buildsign manager

---

internal/mbsc/mbsc.go
internal/mbsc/mbsc_test.go
internal/mbsc/mock_mbsc.go

This API return the status of the an image in the MBSC object based on the image and the action. Is required by the MBSC controller

Adding GetImageStatus API to mbsc package

---

internal/mbsc/mbsc.go

When MBSC object is created/updated by MIC controler , its owner reference should be set with controller=true ,in order to be able to receive events based on the "Own" controller-runtime construct

Fixing MBSC object's owner creation

---

internal/pod/imagepuller.go
internal/pod/imagepuller_test.go
internal/pod/mock_imagepuller.go

This commit contains the following changes:
1. Removing image label - image will be obtained from the Spec directly
2. Adding pod type label - one-time pod that should be considered as Failed once the container fails on image pull, and run-until-success, that is considered as InProgess, in case container ails on image pull
3. Adding GetPodStatus API - this api returns pod status based on the following:
- the pod that fails to pull image stays in the Pending state, and the container status is updated with appropriate reason.So, if the pod is one-time pod, and container failed on image pull - status is Failed. Otherwise status is Running, since we let the pod restart the container with back-offs
4. Pod is created with restartPolicy Never, since if the pod managed to pull image - we consider …

Updating image puller package with the new pod flow

---

internal/buildsign/manager.go
internal/buildsign/mock_manager.go
internal/buildsign/pod/manager.go
internal/buildsign/pod/manager_test.go
internal/controllers/mbsc_reconciler.go
internal/controllers/mbsc_reconciler_test.go

Moving the "owner" input parameter to be the last parameter in order to be aligned with the rest of buildsign manager APIs

Aligning Sync API of the buildsign manager

---

internal/buildsign/pod/manager.go
internal/buildsign/pod/manager_test.go

buildsign/pod is a porting layer, and as such we would like to minimize itsexposure to the outer code. This PR make buildsign manager initialize the maker, signer and buildisngpodmanager interfaces inside its own init function, which will remove the exposure to the porting layer from main

Hiding the buildsign porting layer initialization

---

internal/controllers/nmc_reconciler.go
internal/filter/filter.go
internal/filter/filter_test.go

Node heartbeats are there to let the k8s API server that the node is still connected and functional and if not filtered, it will spam the events the NMC controller gets.
The NMC controller, is trying to garbage collect pods for NMCs that were removed - it causes a constant reconciliation even when no Module, and therefore no NMC, are applied to the cluster.
This commit is fixing this issue.
---

Filtering out node heartbeats events for the NMC controller.

---

internal/mic/mic.go
internal/mic/mic_test.go

In order to receive event from MIC, KMM Module should be the controller of the MIC, and not just an owner

KMM Module should be Owner-Controller of MIC

---

internal/controllers/mic_reconciler.go
internal/controllers/mic_reconciler_test.go

Since adding GetPullPodStatus method to the ImagePuller interface,
which returns the status of the Pod based on its Phase, container's status etc',
the MIC controller has no need to look at the pod itself,
but to just pass it to ImagePuller, and act based on the status returned.
In addition, this PR also adds debug logs to updateStatusByMBSC function

Changing MIC controller to support new ImagePuller interface

---

internal/controllers/mbsc_reconciler.go
internal/controllers/mbsc_reconciler_test.go

Manager interface receives the meta.Object as an input parameter. It passes it to SetControllerReference function, which also expects meta.Object. But inside the function, the it is cast into runtime.Object interface, which requires implementation of DeepCopy function, which is implemented by the whole MBSC object

Passing the MBSC object as an input to buildsign.Manager interface

---

api/v1beta1/nodemodulesconfig_types.go
config/crd/bases/kmm.sigs.x-k8s.io_nodemodulesconfigs.yaml
internal/controllers/mock_nmc_reconciler.go
internal/controllers/nmc_reconciler.go
internal/controllers/nmc_reconciler_test.go
internal/node/mock_node.go
internal/node/node.go
internal/node/node_test.go

KMM loads driver again on node reboot once it detects Node moving from Ready to NotReady back to Ready.
In some cases, like VM node reboot, reboot happens very fast and k8s doesn't report NotReady because of its reporting frequency. Node status, however, has bootID which changes after reboot.
Added support for KMM to detect node reboot using this bootID in cases where reboot happens fast and NotReady state is not reached
Verified that kmm is detecting the boot id change and triggering worker after node is rebooted
```
vm@ubuntu2204:~/kernel-module-management$ kubectl logs -n kube-amd-gpu   amd-gpu-operator-kmm-controller-6fd784d4b4-nfx4z | grep "Detected"
I0328 02:43:46.316244       1 nmc_reconciler.go:348] "Detected BootId change" logger="kmm" controller="NodeModulesConfig" …
```

BootID support for KMM

---

cmd/manager/main.go
config/manager/kustomization.yaml
config/rbac/role.yaml
internal/controllers/mbsc_reconciler.go
internal/controllers/mic_reconciler.go
internal/controllers/module_reconciler.go

changing the manager's main to use MIC and MBSC reconcilers instead of BuildSignReconciler

Switching KMM to work with the new build/sign flow

---

config/manager/kustomization.yaml

This is happening when the operator is tested locally with a custom manager image. We probably missed it during review and merged it by accident.
---

Reverting a config changes that was merged by mistake.

---

internal/controllers/mic_reconciler.go
internal/controllers/mic_reconciler_test.go
internal/pod/imagepuller.go
internal/pod/imagepuller_test.go
internal/pod/mock_imagepuller.go

Since ImagePuller interface is going to be used not only by MIC, but also by Preflight controller, the APIs should be changed to receive specific parameters, and not use ModuleImagesConfig or ImageSpec structures, that are alient to Preflight

Changing ImagePuller interface to more elaborate parameters

---

internal/controllers/module_reconciler.go
internal/controllers/module_reconciler_test.go
internal/mic/mic.go
internal/mic/mic_test.go
internal/mic/mock_mic.go

Now that the MIC object is being reconciled correctly then we can start using the MIC.status in order to check if an image exists instead of using an explicit HTTP request from the controller container.
---

Start using `MIC` status to check if an image exists.

---

.github/workflows/e2e.yaml
ci/kmm-kmod-dockerfile.yaml
ci/prow/e2e-incluster-build
docs/mkdocs/lab/gke/build-configmap.yaml

Ubuntu 20.04 is no longer available in Github's CI. Bumping to the latest version available.
---

Bumping the Github runners Ubuntu version.

---

internal/controllers/nmc_reconciler.go
internal/controllers/nmc_reconciler_test.go
internal/pod/mock_workerpodmanager.go
internal/pod/workerpodmanager.go
internal/pod/workerpodmanager_test.go

Until now, the  nmc status reflected all the worker-pod tolerations, including those unrelated to KMM.
This commit updates the behavior to get tolerations from a dedicated annotation instead, ensuring only KMM-specific tolerations appear in the status.
--- 

Remove non KMM related tolerations from the NMC status

---

internal/build/pod/maker.go
internal/build/pod/maker_test.go
internal/build/pod/manager.go
internal/build/pod/manager_test.go
internal/buildsign/pod/buildsignpodmanager.go
internal/buildsign/pod/buildsignpodmanager_test.go
internal/buildsign/pod/manager.go
internal/buildsign/pod/manager_test.go
internal/controllers/build_sign_events_reconciler.go
internal/controllers/build_sign_events_reconciler_test.go
internal/controllers/job_gc_reconciler.go
internal/sign/pod/manager.go
internal/sign/pod/manager_test.go

We can directly use the API's `BuildImage` and `SignImage`. No need to use local consts and do the translation.
---

Removed the `PodType` consts in the `buildsign` package.

---

api/v1beta1/module_types.go
api/v1beta1/zz_generated.deepcopy.go
config/crd-hub/bases/hub.kmm.sigs.x-k8s.io_managedclustermodules.yaml
config/crd/bases/kmm.sigs.x-k8s.io_modules.yaml
internal/controllers/device_plugin_reconciler.go
internal/controllers/device_plugin_reconciler_test.go
internal/controllers/hub/managedclustermodule_reconciler_test.go
internal/controllers/module_reconciler.go
internal/controllers/module_reconciler_test.go
internal/manifestwork/manifestwork_test.go
internal/module/kernelmapper_test.go
internal/preflight/preflight_test.go
internal/webhook/module.go
internal/webhook/module_test.go

When KMM is used by 3rd party vendor operators, they need an option to configure KMM Module to not load OOT kernel driver, but use the in-tree one, and just run the device-plugin.
This commit makes moduleLoader in Module cr a pointer, and so making it an optional field.
---

Adding support for Modules with no OOT kmod

---

api/v1beta1/moduleimagesconfig_types.go
config/crd/bases/kmm.sigs.x-k8s.io_modulebuildsignconfigs.yaml
config/crd/bases/kmm.sigs.x-k8s.io_moduleimagesconfigs.yaml

Currently, in case image is missing and Build and Sign sections are not defined, MIC controller will keep the image puller pod running and waiting till the images appears. This means that pushing the mising image into the repo will cause the image puller to succeed and the KMM flow will continue running without any need for additional user action. The new field, if set to true, will cause the MIC to report the image as missing and abort the image puller pod (in case Build and Sign sections are not defined). Currently it will be used in the Preflight flow

Adding SkipWaitMissingImage field to MIC Spec

---

config/manager-base/manager.yaml
config/webhook-server/deployment.yaml

Some installations of k8s doesn't allow deploying workloads on the control-plane nodes or the control-plane isn't accessible at all.
In these installs, the worker nodes do not have the node-role.kubernetes.io/control-plane or node-role.kubernetes.io/master labels. Because the worker nodes do not have these labels the Kernel Module Management operator will not run out of the box.
This commit changes the nodeAffinity to
preferredDuringSchedulingIgnoredDuringExecution to solve this issue.
---

Allow KMM to be installed on worker nodes if there is no better choice.

---

internal/controllers/build_sign_reconciler.go
internal/controllers/device_plugin_pod_reconciler.go
internal/controllers/device_plugin_reconciler.go
internal/controllers/mbsc_reconciler.go
internal/controllers/mic_reconciler.go
internal/controllers/module_reconciler.go
internal/controllers/nmc_reconciler.go
internal/controllers/node_kernel_clusterclaim.go
internal/controllers/node_label_module_version_reconciler.go

Until now, RBAC annotations under internal/controllers and internal/controllers/hub were scattered across multiple controller files.
With this commit, the annotations are now centralized only in the Module controller and the MCM controller.
This change addresses the issue where annotations spread across various controllers are applied only to KMM and not to KMM-hub—because all controllers except MCM reside in internal/controllers, and RBAC generation for KMM-hub only scans internal/controllers/hub.
---
/assign @ybettan 

Gathering kmm RBAC annotations in Module controller

---

api/v1beta1/preflightvalidation_types.go
api/v1beta2/preflightvalidation_types.go
config/crd/bases/kmm.sigs.x-k8s.io_preflightvalidations.yaml

Since preflight is moving to MIC/MBSC implementation, the preflight implementation is also changing. MIC is taking over all the handling of build/sign and image verification, so we only need one stage: Image, and the status is now becoming InProgress/Success/Failure

Change Preflight VerifactionStatus and VerifactionStage definitions

---

internal/buildsign/manager.go
internal/controllers/hub/managedclustermodule_reconciler.go
internal/controllers/mbsc_reconciler.go
internal/controllers/module_reconciler.go
internal/controllers/node_label_module_version_reconciler.go
internal/worker/worker.go

In some cases, we were using the args of the formatting string outside of the `fmt.Sprintf()` function which will create a slightly different log than expected.
---

Fixing logging warnings format.

---

docs/mkdocs/documentation/kmod_image.md

It is not currently mentioned in the documentation that the minimal reuirement for the kmod images are to have the `cp` binary present in the image.
---

Adding the `cp` requirement for kmod images documentation.

---

internal/controllers/hub/managedclustermodule_reconciler.go
internal/controllers/hub/managedclustermodule_reconciler_test.go
internal/controllers/module_reconciler.go
internal/controllers/module_reconciler_test.go
internal/controllers/preflightvalidation_reconciler.go
internal/controllers/preflightvalidation_reconciler_test.go
internal/mic/mic.go
internal/mic/mic_test.go
internal/mic/mock_mic.go

imagepuller pod must use the same pull policy as the worker pod, so ImagePullPolicy from from KMM Module must be propagated to the image pulller pod, using MIC CRD and imagepuller interface

propgate the pull policy from MOdule to ImagePuller pod

---

docs/mkdocs/documentation/configure.md
internal/config/config.go

Setting it to `0s` instead of `0` to emphasise the `time.Duration` type instead of a normal `int` which will result in a user error.
Also, explicitly set the `GCDelay` default value so we have all default values in a single place for clarity.
---

Fixing the `GCDelay` configuration option default value documentation.

---

Makefile
config/crd-hub/bases/kmm.sigs.x-k8s.io_modulebuildsignconfigs.yaml
config/crd-hub/bases/kmm.sigs.x-k8s.io_moduleimagesconfigs.yaml
config/crd-hub/bases/kmm.sigs.x-k8s.io_modules.yaml
config/crd-hub/bases/kmm.sigs.x-k8s.io_nodemodulesconfigs.yaml
config/crd-hub/bases/kmm.sigs.x-k8s.io_preflightvalidations.yaml
config/crd-hub/kustomization.yml

KMM-hub only generates CRD files based on the `api-hub/` directory which doesn't contain some CRDs required for KMM-hub such as `MIC` and `MBSC`, therefore, KMM-hub isn't working because it tries to start controllers reconciling CRDs that don't exist in the cluster.
It worked in CI until now because we are using the same single-node cluster as the hub cluster and the spoke cluster so KMM-hub was basically using the CRDs applied by the KMM bundle and not the KMM-hub bundle.
This commit is generating all CRD files into the `config/crd-hub/bases` directory but only applies to the cluster the resources it actually needs.
---

Adding all KMM CRDs generated files to KMM-hub.

---

internal/pod/workerpodmanager.go

The NMC logic ensure we call this function in such a way we never fall into one of the 2 buggy `if` sections.
That said, if the implementation were to change, we could hit this bug in real time, therefore, this method should be fixed.

fixing HashAnnotationDiffer function potential bug

---

ci/prow/operator-hub-upgrade

We need this step in order to install the `manifestwork` and `clusterclaim` CRDs in the cluster.
Without it, `operator-sdk` will still run and manage to do the upgrade but the installed operator will constantly fail due to missing CRDs in the cluster.
This is not affecting the job correctness which is only supposed to test the upgrade but it will make thing much easier if it fails and we need to inspect the "real failing logs" and not the one generated because of missing CRDs.
---

Setting the cluster as a hub cluster.

---

cmd/manager-hub/main.go
cmd/manager/main.go
internal/config/config.go
internal/config/config_test.go

The KMM-hub controller-config configMap had an invalid entry named `metricsBindAddress` in addition to the valid entry which is `metrics.bindAddress`. This issue didn't exist in the KMM controller-config configMap.
As part of making the operators configuration persist operator upgrads, we removed the default controller-config configMaps and changed the way we read the data. The most important part was that we started to parse this data in a strict way, failing in case there is an invalid entry in the data.
When upgrading from 2.3.0 --> 2.4.0, OLM (and operator-sdk) waits for the 2.4.0 to be installed *before* removing 2.3.0, therefore, 2.4.0 was thinking KMM-hub's old controller-config configMap was actually the user's custom config for 2.4.0, and failed due to a non valid field in our …

Fixing KMM-hub's upgrade flow from 2.3.0 --> 2.4.0.

---

api/v1beta1/module_types.go
config/crd-hub/bases/hub.kmm.sigs.x-k8s.io_managedclustermodules.yaml
config/crd-hub/bases/kmm.sigs.x-k8s.io_modulebuildsignconfigs.yaml
config/crd-hub/bases/kmm.sigs.x-k8s.io_moduleimagesconfigs.yaml
config/crd-hub/bases/kmm.sigs.x-k8s.io_modules.yaml
config/crd/bases/kmm.sigs.x-k8s.io_modulebuildsignconfigs.yaml
config/crd/bases/kmm.sigs.x-k8s.io_moduleimagesconfigs.yaml
config/crd/bases/kmm.sigs.x-k8s.io_modules.yaml

As part of transitioning our builds to Shipwright using OCIArtifacts instead of pods running the Kaniko container, we need to allow users to specify the registry and artifact that contain the Dockerfile used for building the kernel module image.
The `dockerfileOCIArtifact` field will remain optional for now, until the migration to Shipwright is complete.
---

Introducing DockerfileOCIArtifact field to Module CRD.

---

go.mod
internal/webhook/module.go
internal/webhook/module_test.go

As part of KMM transitioning to Shipwright, KMM's webhook should allow only the following scenarios:
1. DockerfileOCIArtifact is defined and not DockerfileConfigMap.
2. DockerfileConfigMap is defined and not DockerfileOCIArtifact.
---
/cc @yevgeny-shnaidman @ybettan 
---
/hold
lets wait for #1154

Adjusting webhook for shipwright builds

---

internal/webhook/module.go
internal/webhook/module_test.go

Because we will not use OCIArtifacts with Shipwright for build and sign, we can revert KMM's webhook to not validating DockerfileOCIArtifact in Module.
---
Relevant PR - #1155
---
/cc @ybettan @yevgeny-shnaidman 
/hold

Reverting webhook validation for DockerfileOCIArtifact

---

api/v1beta1/module_types.go
config/crd-hub/bases/hub.kmm.sigs.x-k8s.io_managedclustermodules.yaml
config/crd-hub/bases/kmm.sigs.x-k8s.io_modulebuildsignconfigs.yaml
config/crd-hub/bases/kmm.sigs.x-k8s.io_moduleimagesconfigs.yaml
config/crd-hub/bases/kmm.sigs.x-k8s.io_modules.yaml
config/crd/bases/kmm.sigs.x-k8s.io_modulebuildsignconfigs.yaml
config/crd/bases/kmm.sigs.x-k8s.io_moduleimagesconfigs.yaml
config/crd/bases/kmm.sigs.x-k8s.io_modules.yaml

Because we will not use OCIArtifacts with Shipwright for build and sign, we can revert KMM to use configmap to store the dockerfile.
---
Relevant pr - https://github.com/kubernetes-sigs/kernel-module-management/pull/1154
---
@ybettan @yevgeny-shnaidman

Reverting Module CRD change from using OCIArtifacts to DockerfileConfigMap
